force-app/main/default/objects/Order/fields/Advance_less_than_Payment_Term_committed__c.field-meta.xml
<CustomField>
    <fullName>Advance_less_than_Payment_Term_committed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Advance less than Payment Term committed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Advance_Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advance_Received_Amount__c</fullName>
    <label>Advance Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/CIN_No__c.field-meta.xml
<CustomField>
    <fullName>CIN_No__c</fullName>
    <label>CIN No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Credit_Approval_Check_Required__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval_Check_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Approval Check Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Period__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Period__c</fullName>
    <label>Delivery Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borne by Customer</fullName>
            </value>
            <value>
                <fullName>Borne by IFB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/GST_Certificate_Provided__c.field-meta.xml
<CustomField>
    <fullName>GST_Certificate_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Certificate Provided?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/GST_No__c.field-meta.xml
<CustomField>
    <fullName>GST_No__c</fullName>
    <label>GST No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Installation_Level__c.field-meta.xml
<CustomField>
    <fullName>Installation_Level__c</fullName>
    <label>Installation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Above</fullName>
            </value>
            <value>
                <fullName>Ground Above Basement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PAN_Card_Provided__c.field-meta.xml
<CustomField>
    <fullName>PAN_Card_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PAN Card Provided?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Advance Payment (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Received__c.field-meta.xml
<CustomField>
    <fullName>PO_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCS_Declaration_Form_Provided__c.field-meta.xml
<CustomField>
    <fullName>TCS_Declaration_Form_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TCS Declaration Form Provided?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Warranty_Term_In_Year__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Term_In_Year__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Warranty Term(In Year)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Actual_Delivery_Period__c.field-meta.xml
<CustomField>
    <fullName>Actual_Delivery_Period__c</fullName>
    <label>Actual Delivery Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Includes__c.field-meta.xml
<CustomField>
    <fullName>Freight_Includes__c</fullName>
    <label>Freight Included</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Freight_Terms__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Included in the Quote</fullName>
            </value>
            <value>
                <fullName>Extras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borne by IFB</fullName>
                <default>true</default>
                <label>Borne by IFB</label>
            </value>
            <value>
                <fullName>Borne by Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/GST_No__c.field-meta.xml
<CustomField>
    <fullName>GST_No__c</fullName>
    <formula>Bank_Detail__r.GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Installation_Level__c.field-meta.xml
<CustomField>
    <fullName>Installation_Level__c</fullName>
    <label>Installation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Above</fullName>
            </value>
            <value>
                <fullName>Ground Above Basement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <defaultValue>0.4</defaultValue>
    <label>Advance Payment (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/WarrantyTerm_In_Year__c.field-meta.xml
<CustomField>
    <fullName>WarrantyTerm_In_Year__c</fullName>
    <defaultValue>1</defaultValue>
    <label>WarrantyTerm(In Year)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-1 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>1-2 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>3-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>5-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-10 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>10-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <masterLabel>Delivery Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/POValidationServiceTest.cls
@IsTest
public class POValidationServiceTest {

	@TestSetup
	public static void testPOValidationServiceClass(){
		Test.startTest();
		Account account = TestDataFactory.createAccount();
		User userObj = [SELECT Id From User WHERE Id =: UserInfo.getUserId()];

		Opportunity opp = TestDataFactory.createOpportunityForAccount(account.Id,'Prospecting', userObj);

		SBQQ__Quote__c quote = TestDataFactory.createQuote(opp);
		quote.Freight_Includes__c = 'Included in the Quote';
		quote.SBQQ__Opportunity2__c=opp.Id;
		quote.SBQQ__Primary__c=true;
		quote.Payment_Term__c=40;
		quote.WarrantyTerm_In_Year__c=1;
		quote.Freight_Terms__c='Borne by Customer';
		quote.Actual_Delivery_Period__c = '5-8 weeks';
		update quote;

		Order orderObj = TestDataFactory.createTestOrder(account.Id);
		orderObj.name = 'Test 1';
		orderObj.Status='PO Draft';
		orderObj.EffectiveDate=Date.today();
		orderObj.SBQQ__Quote__c=quote.Id;
		orderObj.PO_Received__c=false;
		orderObj.Credit_Approval_Check_Required__c=false;
		orderObj.GST_Certificate_Provided__c=true;
		orderObj.TCS_Declaration_Form_Provided__c=false;
		orderObj.PAN_Card_Provided__c=true;
		orderObj.Payment_Terms__c=40;
		orderObj.Warranty_Term_In_Year__c=1;
		orderObj.Freight_Terms__c='Borne by Customer';
		orderObj.GST_Certificate_Provided__c = false;
		orderObj.Advance_Received_Amount__c = 10;
		orderObj.Delivery_Period__c = '3-4 weeks';
		update orderObj;

		orderObj = TestDataFactory.createTestOrder(account.Id);
		orderObj.name = 'Test 3';
		orderObj.Status='PO Draft';
		orderObj.EffectiveDate=Date.today();
		orderObj.SBQQ__Quote__c=quote.Id;
		orderObj.PO_Received__c=true;
		orderObj.Credit_Approval_Check_Required__c=true;
		orderObj.GST_Certificate_Provided__c=false;
		orderObj.TCS_Declaration_Form_Provided__c=true;
		orderObj.PAN_Card_Provided__c=true;
		orderObj.Payment_Terms__c=40;
		orderObj.Warranty_Term_In_Year__c=1;
		orderObj.Freight_Terms__c='Borne by Customer';
		orderObj.GST_Certificate_Provided__c = true;
		orderObj.GST_No__c = '06AABCN6808R1ZX';
		orderObj.PAN_No__c = 'AABCN6808R';
		orderObj.CIN_No__c = 'U44003MH1945PLC004403';
		orderObj.Delivery_Period__c = '3-4 weeks';
		orderObj.PAN_Card_Provided__c = false;
		orderObj.Advance_less_than_Payment_Term_committed__c = false;
		orderObj.OwnerId = userObj.Id;
		update orderObj;

		orderObj = TestDataFactory.createTestOrder(account.Id);
		orderObj.name = 'Test 2';
		orderObj.Status='PO Draft';
		orderObj.EffectiveDate=Date.today();
		orderObj.SBQQ__Quote__c=quote.Id;
		orderObj.PO_Received__c=true;
		orderObj.Credit_Approval_Check_Required__c=true;
		orderObj.GST_Certificate_Provided__c=false;
		orderObj.TCS_Declaration_Form_Provided__c=true;
		orderObj.PAN_Card_Provided__c=true;
		orderObj.Payment_Terms__c=1;
		orderObj.Warranty_Term_In_Year__c=2;
		orderObj.Freight_Terms__c='Borne by IFB';
		orderObj.GST_Certificate_Provided__c = true;
		orderObj.GST_No__c = '06AABCN6808R1ZX';
		orderObj.PAN_No__c = 'AABCN6808R';
		orderObj.CIN_No__c = 'U44003MH1945PLC004403';
		orderObj.Delivery_Period__c = '3-4 weeks';
		orderObj.Installation_Level__c = 'Ground';
		orderObj.OwnerId = userObj.Id;
		update orderObj;

		orderObj = TestDataFactory.createTestOrder(account.Id);
		orderObj.name = 'Test 4';
		orderObj.Status='PO Draft';
		orderObj.EffectiveDate=Date.today();
		orderObj.PO_Received__c=true;
		orderObj.Credit_Approval_Check_Required__c=true;
		orderObj.GST_Certificate_Provided__c=false;
		orderObj.TCS_Declaration_Form_Provided__c=true;
		orderObj.PAN_Card_Provided__c=true;
		orderObj.Payment_Terms__c=1;
		orderObj.Warranty_Term_In_Year__c=2;
		orderObj.Freight_Terms__c='Borne by IFB';
		orderObj.GST_Certificate_Provided__c = true;
		orderObj.GST_No__c = '06AABCN6808R1ZX';
		orderObj.PAN_No__c = 'AABCN6808R';
		orderObj.CIN_No__c = 'U44003MH1945PLC004403';
		orderObj.Delivery_Period__c = '3-4 weeks';
		orderObj.Installation_Level__c = 'Ground';
		orderObj.OwnerId = userObj.Id;
		orderObj.Advance_Received_Amount__c = null;
		update orderObj;

		opp = TestDataFactory.createOpportunityForAccount(account.Id,'Prospecting', userObj);
		SBQQ__Quote__c quote1 = TestDataFactory.createQuote(opp);
		quote1.Freight_Includes__c = 'Included in the Quote';
		quote1.SBQQ__Opportunity2__c=opp.Id;
		quote1.SBQQ__Primary__c=true;
		quote1.Payment_Term__c=40;
		quote1.WarrantyTerm_In_Year__c=1;
		quote1.Freight_Terms__c='Borne by Customer';
		update quote1;

		Order order = TestDataFactory.createTestOrderConditionaly(account.Id, false);
		order.Name='Test Order AAAAA';
		order.AccountId=account.Id;
		order.Status='PO Draft';
		order.EffectiveDate=Date.today();
		order.SBQQ__Quote__c=quote.Id;
		order.PO_Received__c=true;
		order.Credit_Approval_Check_Required__c=true;
		order.GST_Certificate_Provided__c=true;
		order.TCS_Declaration_Form_Provided__c=true;
		order.PAN_Card_Provided__c=true;
		order.Payment_Terms__c=40;
		order.Warranty_Term_In_Year__c=1;
		order.Freight_Terms__c='Borne by Customer';
		order.Advance_less_than_Payment_Term_committed__c=false;
		insert order;

		Test.stopTest();
	}

	@IsTest
	public static void testClassMethod(){

		Map<String,Order> mapOfOrders = new Map<String,Order>();
		for(Order orderObj : [SELECT Id, Name From Order WHERE name != 'Test Order AAAAA']){
			mapOfOrders.put(orderObj.Name, orderObj);
		}

		Order orderObj = mapOfOrders.get('Test 1');
		POValidationService.ResponseWrapper result = POValidationService.validatePO(orderObj.Id ,true);
		System.assertEquals(8, result.validationErrors.size());
		orderObj = mapOfOrders.get('Test 3');
		result = POValidationService.validatePO(orderObj.Id  ,true);
		System.assertEquals(2, result.validationErrors.size());
		orderObj = mapOfOrders.get('Test 2');
		result = POValidationService.validatePO(orderObj.Id ,true);
		System.assertEquals(5, result.validationErrors.size());
		POValidationService.validatePO('123' ,true);
		Order tempOrder = new Order();
		result = POValidationService.validatePO(tempOrder.Id ,true);
		System.assertEquals(1, result.validationErrors.size());
		Account accObj = [SELECT Id From Account Limit 1];
		result = POValidationService.validatePO(accObj.Id ,true);
		System.assertEquals(1, result.validationErrors.size());
		orderObj = mapOfOrders.get('Test 4');
		result = POValidationService.validatePO(orderObj.Id ,true);
		System.assertEquals(2, result.validationErrors.size());

	}

	@IsTest
	static void testValidatePO_QueueableJobNotTriggered() {
		Test.startTest();
		Order order = [SELECT Id, Advance_less_than_Payment_Term_committed__c, Freight_Terms__c,
		Warranty_Term_In_Year__c, Payment_Terms__c, PAN_Card_Provided__c
		, TCS_Declaration_Form_Provided__c, GST_Certificate_Provided__c,
		Credit_Approval_Check_Required__c, PO_Received__c, SBQQ__Quote__c, EffectiveDate, Status, AccountId, Name From Order WHERE name = 'Test Order AAAAA' Limit 1];

		POValidationService.ResponseWrapper result = POValidationService.validatePO(order.Id ,true);
		POValidationService.updateOrder(order.Id);
		Test.stopTest();
		System.assertEquals(4, result.validationErrors.size());
		System.assertEquals(0, Limits.getQueueableJobs());
	}
}