force-app/main/default/objects/Product2/fields/HSN_Code__c.field-meta.xml
<CustomField>
    <fullName>HSN_Code__c</fullName>
    <label>HSN Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice</label>
    <nameField>
        <displayFormat>PI-{00000}</displayFormat>
        <label>Proforma Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/fields/Advance_Amount_to_be_collected__c.field-meta.xml
<CustomField>
    <fullName>Advance_Amount_to_be_collected__c</fullName>
    <label>Advance Amount to be collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Balance_Amount_to_be_collected__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount_to_be_collected__c</fullName>
    <label>Balance Amount to be collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST_Value__c.field-meta.xml
<CustomField>
    <fullName>CGST_Value__c</fullName>
    <label>CGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/IGST_Value__c.field-meta.xml
<CustomField>
    <fullName>IGST_Value__c</fullName>
    <label>IGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Po_No__c.field-meta.xml
<CustomField>
    <fullName>Po_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Po No</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Proforma Invoices</relationshipLabel>
    <relationshipName>Proforma_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <label>SGST%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/SGST_Value__c.field-meta.xml
<CustomField>
    <fullName>SGST_Value__c</fullName>
    <label>SGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/Proforma_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice Line Item</label>
    <nameField>
        <displayFormat>IV-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/CGST_Value__c.field-meta.xml
<CustomField>
    <fullName>CGST_Value__c</fullName>
    <label>CGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/HSN_Code__c.field-meta.xml
<CustomField>
    <fullName>HSN_Code__c</fullName>
    <label>HSN Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/Proforma_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice__c</fullName>
    <label>Proforma Invoice</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProformaInvoiceControllerTest.cls
@isTest
private class ProformaInvoiceControllerTest {
    
    @isTest
    static void testProformaInvoiceController() {
        // Create test Account data
        Account testAccount = new Account(
            Name = 'Test Account',
            Phone = '9234567890',
            cgcloud__Account_Number__c = 'Account123',
            BillingStreet = 'Test Street',
            BillingCity = 'jaipur',
            BillingState = 'Rajasthan',
            BillingCountry = 'India',
            BillingPostalCode = '123451',
            ShippingStreet = 'Test Shipping Street',
            ShippingCity = 'jaipur',
            ShippingState = 'Rajasthan',
            ShippingCountry = 'India',
            ShippingPostalCode = '678901'
        );
        insert testAccount;
        
        order testorder = new order(
            AccountId = testAccount.id,
            Name='testorder',
            EffectiveDate=Date.today(),
            Status='SO Created'
        );
        insert testorder;
        // Create test Proforma_Invoice__c data
        Proforma_Invoice__c proformaInvoice = new Proforma_Invoice__c(
            Po_No__r = testorder,
            Total_Amount__c = 1000.00,
            Advance_Amount_to_be_collected__c = 100.00,
            
            Balance_Amount_to_be_collected__c = 900.00
            
        );
        insert proformaInvoice;
        
		Product2 prod = new Product2(
        Name = 'Test Product');
		
		Insert prod;
        // Create test Proforma_Invoice_Line_Item__c data
        Proforma_Invoice_Line_Item__c lineItem = new Proforma_Invoice_Line_Item__c(
            Proforma_Invoice__c = proformaInvoice.Id,
            Product__r = prod,
            Quantity__c = 10,
            Total_Amount__c = 500.00,
            CGST__c = 9.00,
            CGST_Value__c = 45.00,
            SGST__c = 9.00,
            SGST_Value__c = 45.00,
            IGST__c = 18.00,
            IGST_Value__c = 90.00,
            HSN_Code__c = '1234'
        );
        insert lineItem;
        
        // Set the current page parameters to simulate the request
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', proformaInvoice.Id);
        ApexPages.currentPage().getParameters().put('typeofpdf', 'Invoice');
        
        // Instantiate the controller
        ProformaInvoiceController controller = new ProformaInvoiceController();
        
        // Assertions to verify that the controller has been initialized correctly
        System.assertNotEquals(null, controller.wrapperObj);
        System.assertNotEquals(null, controller.wrapperObjAccount);
        System.assertNotEquals(null, controller.invoiceLineItemList);
        System.assertNotEquals(0, controller.invoiceLineItemList.size());
        //System.assertEquals('ORD123', controller.wrapperObj.invoiceNo);
        //System.assertEquals('Test Account', controller.wrapperObjAccount.nameOfConsignee);
        //System.assertEquals('Test Street Test City Test State Test Country 12345', controller.wrapperObjAccount.billingAddress);
        //System.assertEquals(1000.00, controller.wrapperObjLast.totalAmount);
        
        Test.stopTest();
    }
    
    @isTest
    static void testExceptionHandling() {
        // Test scenario where exception is thrown
        Test.startTest();
        
        // Set the current page parameters to simulate the request
        ApexPages.currentPage().getParameters().put('id', 'invalidId');
        
        // Instantiate the controller
        ProformaInvoiceController controller = new ProformaInvoiceController();
        
        // Assertions to check for exception handling
        // As the recordId is invalid, ensure that no wrapper objects are populated
        System.assertEquals(null, controller.wrapperObj);
        System.assertEquals(null, controller.wrapperObjAccount);
        
        Test.stopTest();
    }
}