force-app/main/default/objects/Product2/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/Proforma_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice Line Item</label>
    <nameField>
        <displayFormat>IV-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/Product_Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Sap_Id__c</fullName>
    <label>Product Sap Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProformaInvoiceLineItemTriggerHelper.cls
public class ProformaInvoiceLineItemTriggerHelper {
    public static void beforeInsert(List<Proforma_Invoice_Line_Item__c> newProformaLineItemsList) {
        Set<String> setOfMaterialCodes = new Set<String>();
        List<Product2> listOfProducts = new List<Product2>();
        Map<String, Product2> productMap = new Map<String, Product2>();
        try{
            for (Proforma_Invoice_Line_Item__c lineItem : newProformaLineItemsList) {
                if (lineItem.Product_Sap_Id__c != null) {
                    setOfMaterialCodes.add(lineItem.Product_Sap_Id__c);
                }
            }
            if(!setOfMaterialCodes.isEmpty()){
                listOfProducts = [SELECT Id, Material_Code__c FROM Product2 WHERE Material_Code__c IN :setOfMaterialCodes];
            }
            if(!listOfProducts.isEmpty()){
                for(Product2 prodRecord : listOfProducts){
                    productMap.put(prodRecord.Material_Code__c,prodRecord);
                }
                
            }
            for (Proforma_Invoice_Line_Item__c lineItem : newProformaLineItemsList) {
                if (lineItem.Product_Sap_Id__c != null) {
                    Product2 matchedProduct = productMap.get(lineItem.Product_Sap_Id__c);
                    if (matchedProduct != null) {
                        lineItem.Product__c = matchedProduct.Id;
                    } else {
                        throw new TriggerException('No matching product found for Material Code in Salesforce: ' + lineItem.Product_Sap_Id__c);
                    }
                }
            } 
        }
        catch(Exception e){
            ExceptionHandler.logException('ProformaInvoiceLineItemTriggerHelper', 'beforeInsert', e);
        }
    }
}