force-app/main/default/objects/Product2/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice</label>
    <nameField>
        <displayFormat>PI-{00000}</displayFormat>
        <label>Proforma Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/Proforma_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice Line Item</label>
    <nameField>
        <displayFormat>IV-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/Product_Sap_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Sap_Id__c</fullName>
    <label>Product Sap Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice_Line_Item__c/fields/Proforma_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice__c</fullName>
    <label>Proforma Invoice</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProformaInvoiceLineItemTriggerTest.cls
@isTest
public class ProformaInvoiceLineItemTriggerTest {
    @testSetup
    static void setupTestData() {
        Product2 prod = TestDataFactory.createProduct('1121', 'Test prod', 'Test Prod');
        Proforma_Invoice__c pi = TestDataFactory.createProformaInvoice(100);
        TestDataFactory.createLineItem('1121', pi.Id);
       
    }
    @isTest
    public static void beforeInsert(){
        Product2 prod = [SELECT Id, Name, Description, Material_Code__c 
                         FROM Product2 
                         WHERE Material_Code__c = '1121' 
                         LIMIT 1];
        
        List<Proforma_Invoice_Line_Item__c> lineItems = [
            SELECT Id, Product_Sap_Id__c, Proforma_Invoice__c 
            FROM Proforma_Invoice_Line_Item__c WHERE Product_Sap_Id__c = '1121'
        ];
        System.assertEquals(1, lineItems.size(), 'Proforma Invoice Line Items should be present.');
        System.assertNotEquals(0, lineItems.size(), 'Proforma Invoice Line Items should be present.');
    }
    @isTest
    public static void testUpdate(){
        List<Proforma_Invoice_Line_Item__c> lineItems = [
            SELECT Id, Product_Sap_Id__c, Proforma_Invoice__c 
            FROM Proforma_Invoice_Line_Item__c WHERE Product_Sap_Id__c = '1121'
        ];
        lineItems[0].Product_Sap_Id__c = '1321';
        update lineItems;
        delete lineItems;
    }
    @isTest
    public static void testBeforeUpdate(){
        List<Proforma_Invoice_Line_Item__c> lineItems = [
            SELECT Id, Product_Sap_Id__c, Proforma_Invoice__c 
            FROM Proforma_Invoice_Line_Item__c WHERE Product_Sap_Id__c = '1121'
        ];
        Map<ID, Proforma_Invoice_Line_Item__c> oldProformaLineItemsMap = new Map<ID, Proforma_Invoice_Line_Item__c>();
        for(Proforma_Invoice_Line_Item__c pi : lineItems){
            oldProformaLineItemsMap.put(pi.Id,pi);
        }
        Test.startTest();
        ProformaInvoiceLineItemTriggerHandler handler = new ProformaInvoiceLineItemTriggerHandler();
        handler.beforeInsert(lineItems);
        handler.beforeUpdate(lineItems, lineItems, oldProformaLineItemsMap, oldProformaLineItemsMap);
        handler.beforeDelete(lineItems, oldProformaLineItemsMap);
        handler.afterInsert(lineItems, oldProformaLineItemsMap);
        handler.afterUpdate(lineItems, lineItems, oldProformaLineItemsMap, oldProformaLineItemsMap);
        handler.afterDelete(lineItems, oldProformaLineItemsMap);
        handler.afterUndelete(lineItems, oldProformaLineItemsMap);
        Test.stopTest();
    }
}