force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Educational Institutions</fullName>
            </value>
            <value>
                <fullName>Establishments</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Garment</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>HNI</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Laundromats</fullName>
            </value>
            <value>
                <fullName>List Of Ministries</fullName>
            </value>
            <value>
                <fullName>Non-Profit Organization/NGO</fullName>
            </value>
            <value>
                <fullName>Organization/Entity</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Railway</fullName>
                <isActive>false</isActive>
                <label>Railway</label>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Sub_segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sub_segment__c</fullName>
    <label>Customer Sub segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture and Farmers Welfare</fullName>
            </value>
            <value>
                <fullName>Airbnb</fullName>
            </value>
            <value>
                <fullName>Airways</fullName>
            </value>
            <value>
                <fullName>Ayurvedic Hospital</fullName>
            </value>
            <value>
                <fullName>AYUSH</fullName>
            </value>
            <value>
                <fullName>Banking &amp; Financial Services Institutions</fullName>
            </value>
            <value>
                <fullName>Banquets</fullName>
            </value>
            <value>
                <fullName>Caterers</fullName>
            </value>
            <value>
                <fullName>Chain of Hotels</fullName>
            </value>
            <value>
                <fullName>Chain of Laundromat - FOFO/COCO</fullName>
            </value>
            <value>
                <fullName>Chain of Restaurants</fullName>
            </value>
            <value>
                <fullName>Chemicals and Fertilizers</fullName>
            </value>
            <value>
                <fullName>Civil Aviation</fullName>
            </value>
            <value>
                <fullName>Clubs</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>College</fullName>
            </value>
            <value>
                <fullName>Commerce and Industry</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Consultant - Architect/PMC Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Design Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Kitchen Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Laundry Consultant</fullName>
            </value>
            <value>
                <fullName>Consumer Affairs, Food and Public Distribution</fullName>
            </value>
            <value>
                <fullName>Contractors - Building contractors</fullName>
            </value>
            <value>
                <fullName>Contractors - Canteen contractors</fullName>
            </value>
            <value>
                <fullName>Contractors - Laundry contractors</fullName>
            </value>
            <value>
                <fullName>Contractors - MES contractors</fullName>
            </value>
            <value>
                <fullName>Convention Centers</fullName>
                <isActive>false</isActive>
                <label>Convention Centers</label>
            </value>
            <value>
                <fullName>Conventional centers</fullName>
                <label>Convention Centre</label>
            </value>
            <value>
                <fullName>Cooperation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Business__c.field-meta.xml
<CustomField>
    <fullName>Other_Business__c</fullName>
    <label>Other Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Locations_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Other_Locations_if_applicable__c</fullName>
    <label>Other Locations, if applicable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/Integration_Handler__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type will be used to store the credential and other details  of third party system.</description>
    <label>Integration Handler</label>
    <pluralLabel>Integration Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Handler__mdt/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Static_Token_Value__c.field-meta.xml
<CustomField>
    <fullName>Static_Token_Value__c</fullName>
    <inlineHelpText>Bearer Token which will get user for authentication</inlineHelpText>
    <label>Static Token Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget availability and Budget Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, Own Source</fullName>
            </value>
            <value>
                <fullName>Yes, Loan Approved</fullName>
            </value>
            <value>
                <fullName>Loan In Progress</fullName>
            </value>
            <value>
                <fullName>Budget not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CurrentValidationTime__c.field-meta.xml
<CustomField>
    <fullName>CurrentValidationTime__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>CurrentValidationTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score__c</fullName>
    <formula>(
IF(TEXT( Purchase_timeline__c ) = &quot;0-30 days&quot;, 0.35,
IF(TEXT(Purchase_timeline__c ) = &quot;31-60 days&quot;, 0.20,
IF(TEXT(Purchase_timeline__c ) = &quot;61-90 days&quot;, 0.10,
IF(TEXT(Purchase_timeline__c ) = &quot;greater than 90 days&quot;, 0, 0)
)
)
) +
IF(TEXT( Budget__c ) = &quot;Yes, Own Source&quot;, 0.35,
IF(TEXT(Budget__c ) = &quot;Yes, Loan Approved&quot;, 0.35,
IF(TEXT(Budget__c ) = &quot;Loan In Progress&quot;, 0.20,
IF(TEXT(Budget__c ) = &quot;Budget not available&quot;, 0, 0)
)
)
) +
IF(TEXT( Space_availability__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Space_availability__c ) = &quot;NO&quot;, 0, 0)
) +
IF(TEXT( Site__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Site__c ) = &quot;NO&quot;, 0, 0)
) +
IF(TEXT( Infrastructure_completed_in_30_days__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Infrastructure_completed_in_30_days__c ) = &quot;NO&quot;, 0, 0)
)
)</formula>
    <label>Lead Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LeadIDText__c.field-meta.xml
<CustomField>
    <fullName>LeadIDText__c</fullName>
    <label>LeadIDText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_Follow_up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_up_Date_Time__c</fullName>
    <label>Next Follow-up Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_timeline__c</fullName>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-30 days</fullName>
            </value>
            <value>
                <fullName>31-60 days</fullName>
            </value>
            <value>
                <fullName>61-90 days</fullName>
            </value>
            <value>
                <fullName>greater than 90 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
                <isActive>false</isActive>
                <label>Frozen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Space_availability__c.field-meta.xml
<CustomField>
    <fullName>Space_availability__c</fullName>
    <label>Space Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Setup__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Setup__c</fullName>
    <label>Type of Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Setup</fullName>
            </value>
            <value>
                <fullName>Existing Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdobeOppSyncBatch.cls
/**
* @File Name : AdobeOppSyncBatch.cls
* @Description :
* @Author : Aakash
* @Last Modified By :
* @Last Modified On : February 13, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | February 13, 2025 |   | Initial Version
**/

global class AdobeOppSyncBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable  {
	global Database.QueryLocator start(Database.BatchableContext bc){
		return Database.getQueryLocator([ SELECT Id, StageName,LeadSource, Rating__c, Next_Follow_up_Date_Time__c, Purchase_timeline__c, Site__c, Space_Availability__c, 
       LeadIDText__c,Lead_Score__c,Adobe_Sync__c, Product_category__c, Type, Type_of_Customer__c, Name, Budget__c, Type_of_Setup__c, Account.Name,
       Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingCountry, Account.BillingPostalCode, 
       Account.ShippingStreet, Account.ShippingCity, Account.ShippingState, Account.ShippingCountry, Account.ShippingPostalCode, 
       Account.AnnualRevenue, Account.Website, Account.Other_Business__c, Account.Other_Locations_if_applicable__c, 
       Account.Sector__c, Account.Customer_Segment__c, AccountId,Account.Customer_Sub_segment__c,CreatedDate FROM 
       Opportunity Where (StageName=:ConstantUtilities.OPP_STAGE_QUALIFICATION OR StageName=:ConstantUtilities.OPP_STAGE_SITE_VISIT OR StageName=:ConstantUtilities.OPP_STAGE_LOAD_CALCULATION) AND LeadIDText__c!=null AND AccountId!=null AND Adobe_Sync__c=false AND  CreatedDate < LAST_N_DAYS:2]);
	}
	global void execute(Database.BatchableContext bc,List<Opportunity> oppBatch){
        Integration_Handler__mdt intHandlerInst = Integration_Handler__mdt.getInstance(ConstantUtilities.ADOBE_LEAD_SYNC);
         List<AdobeLeadSync.LeadWrapper> oppWrapperList = new List<AdobeLeadSync.LeadWrapper>();
        try{
            oppWrapperList = AdobeLeadSync.getOppData(oppBatch);
        }catch(exception e){
            insert Utilities.getExceptionErrorLog('AdobeOppSyncBatch', 'execute', e);
        }
		
		String requestBody = JSON.serialize(oppWrapperList);
		HttpRequest req = new HttpRequest();
		req.setEndpoint(intHandlerInst.URL__c);
		req.setMethod(intHandlerInst.Http_Method__c);
		req.setHeader('Content-Type', 'application/json');
		req.setHeader('Authorization', 'Bearer '+ intHandlerInst.Static_Token_Value__c);
		req.setBody(requestBody);

		Http http = new Http();
        HttpResponse res;
        String responseBody = '';
		try{
			res = http.send(req);
            system.debug(res);
            System.debug('Response Status: ' + res.getStatus());
			System.debug('Response Body: ' + res.getBody());
			if (res.getStatusCode() == 200 || res.getStatusCode() == 201) {
                insert Utilities.getInfoLog('AdobeOppSyncBatch' , 'executeInfo', requestBody,'Status Code-'+res.getStatusCode()+' \n Body-'+res.getBody());
                responseBody = res.getBody();
            } else {
                throw new CalloutException('Error in response: ' + res.getStatus());
            }
		}catch (Exception e) {
            insert Utilities.getInfoLog('AdobeOppSyncBatch' , 'ErrorInfo', requestBody,'Status Code-'+res.getStatusCode()+' \n Body-'+res.getBody());
        }
        
        Map<String,Opportunity> oppMap = new Map<String,Opportunity>();
        for(Opportunity opp:oppBatch){
            oppMap.put(opp.LeadIDText__c,opp);
        }
        AdobeLeadSyncResponse responseObj = new AdobeLeadSyncResponse();
        try{
            responseObj = AdobeLeadSyncResponse.parseResponse(responseBody);
            List<Opportunity> oppToUpdateList = new List<Opportunity>();
            for(AdobeLeadSyncResponse.LeadResponse leadRes:responseObj.data){
                if(oppMap.containsKey(leadRes.leadId) && leadRes.status==ConstantUtilities.RES_STATUS_SUCCESS){
                    Opportunity oppToUpdate = oppMap.get(leadRes.leadId);
                    oppToUpdate.Adobe_Sync__c = True;
                    oppToUpdate.Adobe_Sync_Time__c  = system.now();
                    oppToUpdate.CurrentValidationTime__c = system.now();
                    oppToUpdateList.add(oppToUpdate);
                }
            }
            List<Database.SaveResult> srList = new List<Database.SaveResult>();
            if (!oppToUpdateList.isEmpty()) {
              srList= Database.update(oppToUpdateList,false);
                 for(Database.SaveResult sr:srList){
                    if(sr.isSuccess()){
                        insert Utilities.getInfoLog('AdobeOppSyncBatch' , 'UpdateInfoLog', 'True','Status Code-'+res.getStatusCode()+' \n Body-'+sr.getId());

                    }else{
                        insert Utilities.getInfoLog('AdobeOppSyncBatch' , 'UpdateErrorInfoLog', 'True','Status Code-'+res.getStatusCode()+' \n Body-'+sr.getErrors());
                    }

                }
            }
        }catch(exception e){
            insert Utilities.getInfoLog('AdobeOppSyncBatch' , 'ErrorInfo', requestBody,'Status Code-'+res.getStatusCode()+' \n Body-'+res.getBody());
            
        }
		
	}
	global void finish(Database.BatchableContext bc){
        
	}
     global void execute(SchedulableContext sc) {
        Database.executeBatch(new AdobeOppSyncBatch(), 100);
    }
    
}