force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Educational Institutions</fullName>
            </value>
            <value>
                <fullName>Establishments</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Garment</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>HNI</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Laundromats</fullName>
            </value>
            <value>
                <fullName>List Of Ministries</fullName>
            </value>
            <value>
                <fullName>Non-Profit Organization/NGO</fullName>
            </value>
            <value>
                <fullName>Organization/Entity</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Railway</fullName>
                <isActive>false</isActive>
                <label>Railway</label>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Business__c.field-meta.xml
<CustomField>
    <fullName>Other_Business__c</fullName>
    <label>Other Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Locations_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Other_Locations_if_applicable__c</fullName>
    <label>Other Locations, if applicable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Adobe_Sync__c.field-meta.xml
<CustomField>
    <fullName>Adobe_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adobe Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score__c</fullName>
    <formula>(
  IF(TEXT(Purchase_Timeline__c) = &quot;0-30 days&quot;, 0.35,
    IF(TEXT(Purchase_Timeline__c) = &quot;31-60 days&quot;, 0.20,
      IF(TEXT(Purchase_Timeline__c) = &quot;61-90 days&quot;, 0.10,
        IF(TEXT(Purchase_Timeline__c) = &quot;greater than 90 days&quot;, 0, 0)
      )
    )
  ) +
  IF(TEXT(Budget_Availablility_Budget_Source__c) = &quot;Yes, Own Source&quot;, 0.35,
    IF(TEXT(Budget_Availablility_Budget_Source__c) = &quot;Yes, Loan Approved&quot;, 0.35,
      IF(TEXT(Budget_Availablility_Budget_Source__c) = &quot;Loan In Progress&quot;, 0.20,
        IF(TEXT(Budget_Availablility_Budget_Source__c) = &quot;Budget not available&quot;, 0, 0)
      )
    )
  ) +
  IF(TEXT(Space_Availability__c) = &quot;YES&quot;, 0.10,
    IF(TEXT(Space_Availability__c) = &quot;NO&quot;, 0, 0)
  ) +
  IF(TEXT(Site_Suitability__c) = &quot;YES&quot;, 0.10,
    IF(TEXT(Site_Suitability__c) = &quot;NO&quot;, 0, 0)
  ) +
  IF(TEXT(Infrastructure_completed_in_30_days__c) = &quot;YES&quot;, 0.10,
    IF(TEXT(Infrastructure_completed_in_30_days__c) = &quot;NO&quot;, 0, 0)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>ILE</fullName>
                <isActive>false</isActive>
                <label>ILE</label>
            </value>
            <value>
                <fullName>Industrial Dishwasher</fullName>
                <isActive>false</isActive>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Industrial Laundry Machine</fullName>
                <isActive>false</isActive>
                <label>Industrial Laundry Machine</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purchase_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Timeline__c</fullName>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-30 days</fullName>
            </value>
            <value>
                <fullName>31-60 days</fullName>
            </value>
            <value>
                <fullName>61-90 days</fullName>
            </value>
            <value>
                <fullName>greater than 90 days</fullName>
                <label>Greater than 90 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Space_Availability__c.field-meta.xml
<CustomField>
    <fullName>Space_Availability__c</fullName>
    <label>Space Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Domestic</fullName>
                <isActive>false</isActive>
                <label>Domestic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget availability and Budget Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, Own Source</fullName>
            </value>
            <value>
                <fullName>Yes, Loan Approved</fullName>
            </value>
            <value>
                <fullName>Loan In Progress</fullName>
            </value>
            <value>
                <fullName>Budget not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score__c</fullName>
    <formula>(
IF(TEXT( Purchase_timeline__c ) = &quot;0-30 days&quot;, 0.35,
IF(TEXT(Purchase_timeline__c ) = &quot;31-60 days&quot;, 0.20,
IF(TEXT(Purchase_timeline__c ) = &quot;61-90 days&quot;, 0.10,
IF(TEXT(Purchase_timeline__c ) = &quot;greater than 90 days&quot;, 0, 0)
)
)
) +
IF(TEXT( Budget__c ) = &quot;Yes, Own Source&quot;, 0.35,
IF(TEXT(Budget__c ) = &quot;Yes, Loan Approved&quot;, 0.35,
IF(TEXT(Budget__c ) = &quot;Loan In Progress&quot;, 0.20,
IF(TEXT(Budget__c ) = &quot;Budget not available&quot;, 0, 0)
)
)
) +
IF(TEXT( Space_availability__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Space_availability__c ) = &quot;NO&quot;, 0, 0)
) +
IF(TEXT( Site__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Site__c ) = &quot;NO&quot;, 0, 0)
) +
IF(TEXT( Infrastructure_completed_in_30_days__c ) = &quot;YES&quot;, 0.10,
IF(TEXT(Infrastructure_completed_in_30_days__c ) = &quot;NO&quot;, 0, 0)
)
)</formula>
    <label>Lead Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LeadIDText__c.field-meta.xml
<CustomField>
    <fullName>LeadIDText__c</fullName>
    <label>LeadIDText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_Follow_up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_up_Date_Time__c</fullName>
    <label>Next Follow-up Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_timeline__c</fullName>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-30 days</fullName>
            </value>
            <value>
                <fullName>31-60 days</fullName>
            </value>
            <value>
                <fullName>61-90 days</fullName>
            </value>
            <value>
                <fullName>greater than 90 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
                <isActive>false</isActive>
                <label>Frozen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Space_availability__c.field-meta.xml
<CustomField>
    <fullName>Space_availability__c</fullName>
    <label>Space Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Setup__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Setup__c</fullName>
    <label>Type of Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Setup</fullName>
            </value>
            <value>
                <fullName>Existing Setup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdobeLeadSyncBatchTest.cls
@isTest
public class AdobeLeadSyncBatchTest {

    @testSetup
    static void setupTestData() {
        Account acc = TestDataFactory.createAccount();
        Contact con  = TestDataFactory.createContactForAccount(acc.Id, 'test@mail.com');
        Lead leadL = TestDataFactory.createLead();
        Opportunity opp1 =TestDataFactory.createOpportunityConditionaly(acc.Id, 'Qualification', false);
        opp1.LeadIDText__c = leadL.Id;

        Opportunity opp2 = TestDataFactory.createOpportunityConditionaly(acc.Id, 'Qualification', false);
        opp2.LeadIDText__c = leadL.Id;
        insert new List<Opportunity>{ opp1, opp2 };
        List<Lead> testLeads = TestDataFactory.createLeadList();
    }

    @isTest
    static void testExecuteMethod() {
        Test.setMock(HttpCalloutMock.class, new AdobeLeadSyncMock());
        List<Opportunity> oppList = [ SELECT Id, StageName, LeadSource, Rating__c, Next_Follow_up_Date_Time__c, Purchase_timeline__c, Site__c, Space_Availability__c, 
       LeadIDText__c,Lead_Score__c,Adobe_Sync__c, Product_category__c, Type, Type_of_Customer__c, Name, Budget__c, Type_of_Setup__c, Account.Name,
       Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingCountry, Account.BillingPostalCode, 
       Account.ShippingStreet, Account.ShippingCity, Account.ShippingState, Account.ShippingCountry, Account.ShippingPostalCode, 
       Account.AnnualRevenue, Account.Website, Account.Other_Business__c, Account.Other_Locations_if_applicable__c, 
       Account.Sector__c, Account.Customer_Segment__c, AccountId,Account.Customer_Sub_segment__c
FROM Opportunity where LeadIDText__c!=null AND AccountId!=null AND Adobe_Sync__c=false];
        
        List<Lead> testLeads = [SELECT Id, Status, Lead_Score__c, Rating, Next_Follow_up_Date_Time__c, Requirement__c ,Purchase_Timeline__c, Site_Suitability__c, Space_Availability__c,
                                    LeadSource,  Lead_Sub_Source__c,  Product_Category__c,  Type__c, 
                                    Type_of_Customer__c, 
                                    FirstName, LastName, Company, Phone,Alternative_Phone_Number__c, Email, 
                                    Is_our_contact_a_Key_Decision_Maker__c,  Customer_Department__c, Customer_Designation__c,
                                    Street, City, State, PostalCode, Country,
                                    Shipping__Street__s, Shipping__City__s,Shipping__StateCode__s, Shipping__PostalCode__s, Shipping__CountryCode__s,
                                    Name,  Sector__c, Customer_Segment_Vertical__c, Customer_Sub_segment_Sub_Vertical__c, 
                                    Other_Business__c, Other_Locations__c, Region_Name__c, 
                                    Type_of_Setup__c, AnnualRevenue,  Website,CreatedDate from lead ];

        Test.startTest();
        AdobeLeadSyncBatch leadBatch = new AdobeLeadSyncBatch();
        leadBatch.execute(null, testLeads);
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Adobe_Sync__c FROM Lead WHERE Adobe_Sync__c = true];
    }

    @isTest
    static void testSchedulableExecuteMethod() {
        Test.startTest();
        AdobeLeadSyncBatch batch = new AdobeLeadSyncBatch();
        //batch.execute(null);
        Test.stopTest();
    }

    private class AdobeLeadSyncMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"data":[{"leadId":"' + [SELECT Id FROM Lead LIMIT 1].Id + '","status":"SUCCESS"}]}');
            return res;
        }
    }
    
     @isTest
    static void testScheduledBatchExecution() {
        String cronExp = '0 0 12 * * ?';

        String jobId = System.schedule('Test Adobe Lead Sync Job', cronExp, new AdobeLeadSyncBatch());

        Test.startTest();
        Test.stopTest();

        System.assertNotEquals(null, jobId, 'Scheduled job ID should not be null.');
    }
    
    
}