force-app/main/default/objects/Account/fields/PreInstallationUpdateAllow__c.field-meta.xml
<CustomField>
    <fullName>PreInstallationUpdateAllow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PreInstallationUpdateAllow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drain_Outlet_Size_Gravity_Drain_Req__c.field-meta.xml
<CustomField>
    <fullName>Drain_Outlet_Size_Gravity_Drain_Req__c</fullName>
    <label>Drain Outlet Size-Gravity Drain Req.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Electric_Connection_Incoming_Supp_Vol__c.field-meta.xml
<CustomField>
    <fullName>Electric_Connection_Incoming_Supp_Vol__c</fullName>
    <label>Electric Connection (Incoming Supp Vol.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Machine_Dimensions_w_d_h_Space_Req__c.field-meta.xml
<CustomField>
    <fullName>Machine_Dimensions_w_d_h_Space_Req__c</fullName>
    <label>Machine Dimensions (w*d*h) -Space Req.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MCB_Rating__c.field-meta.xml
<CustomField>
    <fullName>MCB_Rating__c</fullName>
    <label>MCB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PreInstallationRequired__c.field-meta.xml
<CustomField>
    <fullName>PreInstallationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PreInstallationRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Required_Intel_Water_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Required_Intel_Water_Pressure__c</fullName>
    <label>Required Intel  Water Pressure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Required_Power_Cable_Size_Rating__c.field-meta.xml
<CustomField>
    <fullName>Required_Power_Cable_Size_Rating__c</fullName>
    <label>Required Power Cable(Size/Rating)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Power_Req_Connected_Load__c.field-meta.xml
<CustomField>
    <fullName>Total_Power_Req_Connected_Load__c</fullName>
    <label>Total Power Req.(Connected Load)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Water_Hardness__c.field-meta.xml
<CustomField>
    <fullName>Water_Hardness__c</fullName>
    <label>Water Hardness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Water_Intel_Size_With_Ball_Value_M_T_S__c.field-meta.xml
<CustomField>
    <fullName>Water_Intel_Size_With_Ball_Value_M_T_S__c</fullName>
    <label>Water Intel Size With Ball Value(M.T.S.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityIDWTableComponentController.cls
/*
@Author : Yadram
@CreatedDate : 14th June 2024
@Description : This controller is use to fetch the  Opportunity of IDW Product for Pre Installtion Checklist  

*/
public class OpportunityIDWTableComponentController {
    
    @AuraEnabled(cacheable=true)
    public static Opportunity getOppRecord(String oppRecordId){
        try{
            Opportunity oppRecord = [SELECT Id,Name,Owner.Name, Machine_Dimensions_w_d_h_Space_Req__c, Total_Power_Req_Connected_Load__c, 
                                     Electric_Connection_Incoming_Supp_Vol__c, MCB_Rating__c, Required_Power_Cable_Size_Rating__c, 
                                     Water_Hardness__c,Required_Intel_Water_Pressure__c, Water_Intel_Size_With_Ball_Value_M_T_S__c, 
                                     Drain_Outlet_Size_Gravity_Drain_Req__c , Model__c From Opportunity WHERE Id =: oppRecordId Limit 1];
            
            return oppRecord;
        }
        catch(Exception e){
            ExceptionHandler.logException('OpportunityIDWTableComponentController', 'getOppRecord', e);
        }   
        return null;
    }
    
    @AuraEnabled 
    public static string saveRecord(Opportunity oppRecordFromLwc){
        try{
            if(oppRecordFromLwc != Null){
                Account acccount = new Account();
                Opportunity opp = [ SELECT Account.Id  FROM Opportunity WHERE Id = :oppRecordFromLwc.Id LIMIT 1 ];
                if (opp.AccountId != null) {
                    acccount = new Account(
                        Id = opp.Account.Id,  
                        PreInstallationUpdateAllow__c = True
                    );
                    update acccount;
                }
                if(oppRecordFromLwc.Machine_Dimensions_w_d_h_Space_Req__c != null && oppRecordFromLwc.Total_Power_Req_Connected_Load__c != null &&
                   oppRecordFromLwc.Electric_Connection_Incoming_Supp_Vol__c != null &&oppRecordFromLwc.MCB_Rating__c != null && 
                   oppRecordFromLwc.Required_Power_Cable_Size_Rating__c != null && oppRecordFromLwc.Water_Hardness__c != null && 
                   oppRecordFromLwc.Required_Intel_Water_Pressure__c != null && oppRecordFromLwc.Water_Intel_Size_With_Ball_Value_M_T_S__c != null && 
                   oppRecordFromLwc.Drain_Outlet_Size_Gravity_Drain_Req__c != null &&  oppRecordFromLwc.Model__c != null
                  ){
                      oppRecordFromLwc.PreInstallationRequired__c = True; 
                  }
                Update oppRecordFromLwc;
                
                if (opp.AccountId != null) {
                    acccount = new Account(
                        Id = opp.Account.Id,  
                        PreInstallationUpdateAllow__c = false
                    );
                    update acccount;
                } 
            
        }
        return 'Success';
    }
    catch(Exception e){
        ExceptionHandler.logException('OpportunityIDWTableComponentController', 'saveRecord', e);
        return e.getMessage();
    }   
}
}