force-app/main/default/objects/Account/fields/Sub_type_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Sub_type_of_Account__c</fullName>
    <label>Sub type of Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Account - High Value Customers</fullName>
            </value>
            <value>
                <fullName>PAN India Presence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Account__c</fullName>
    <label>Type of Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Existing Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Air_Line_Provision__c.field-meta.xml
<CustomField>
    <fullName>Air_Line_Provision__c</fullName>
    <label>Air Line Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BOQ_Machine_List__c.field-meta.xml
<CustomField>
    <fullName>BOQ_Machine_List__c</fullName>
    <label>BOQ/Machine List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Hot_Air_Exhaust_Provision__c.field-meta.xml
<CustomField>
    <fullName>Check_Hot_Air_Exhaust_Provision__c</fullName>
    <label>Check Hot Air Exhaust Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Provision_for_Ventilation_in_Room__c.field-meta.xml
<CustomField>
    <fullName>Check_Provision_for_Ventilation_in_Room__c</fullName>
    <label>Check Provision for Ventilation in Room</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Room_Height__c.field-meta.xml
<CustomField>
    <fullName>Check_Room_Height__c</fullName>
    <label>Check Room Height</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Utility_Connection_Availability__c.field-meta.xml
<CustomField>
    <fullName>Check_Utility_Connection_Availability__c</fullName>
    <label>Check Utility Connection / Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Water_Hardness__c.field-meta.xml
<CustomField>
    <fullName>Check_Water_Hardness__c</fullName>
    <label>Check Water Hardness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Check_Water_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Check_Water_Pressure__c</fullName>
    <label>Check Water Pressure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clear_Passage_for_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Clear_Passage_for_Vehicle__c</fullName>
    <inlineHelpText>Check clear passage for vehicle
 (Truck &amp; Crane) movement &amp; Unloading.</inlineHelpText>
    <label>Clear Passage for Vehicle?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Not OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drainage__c.field-meta.xml
<CustomField>
    <fullName>Drainage__c</fullName>
    <label>Drainage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Electric_Connection_Incoming_Supp_Vol__c.field-meta.xml
<CustomField>
    <fullName>Electric_Connection_Incoming_Supp_Vol__c</fullName>
    <label>Electric Connection (Incoming Supp Vol.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Electrical_Provision__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Provision__c</fullName>
    <label>Electrical Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Heating_Type__c.field-meta.xml
<CustomField>
    <fullName>Heating_Type__c</fullName>
    <label>Heating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Dual (Electric &amp; Steam)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/If_To_be_built_please_share_details__c.field-meta.xml
<CustomField>
    <fullName>If_To_be_built_please_share_details__c</fullName>
    <label>If &quot;To be built&quot; please share details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Construction started</fullName>
            </value>
            <value>
                <fullName>Not yet started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Installation_Except_GF_LB__c.field-meta.xml
<CustomField>
    <fullName>Installation_Except_GF_LB__c</fullName>
    <inlineHelpText>Except Ground floor / Lower level Basement . If installation in any other floors, ensure to provide static &amp; dynamic load details.</inlineHelpText>
    <label>Installation Except GF/LB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Laundry_Set_up__c.field-meta.xml
<CustomField>
    <fullName>Laundry_Set_up__c</fullName>
    <label>Laundry Set up</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Machine_Dimensions_w_d_h_Space_Req__c.field-meta.xml
<CustomField>
    <fullName>Machine_Dimensions_w_d_h_Space_Req__c</fullName>
    <label>Machine Dimensions (w*d*h) -Space Req.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Machine_Installation_Floor_Level__c.field-meta.xml
<CustomField>
    <fullName>Machine_Installation_Floor_Level__c</fullName>
    <label>Machine Installation Floor Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lower Basement</fullName>
            </value>
            <value>
                <fullName>GF</fullName>
            </value>
            <value>
                <fullName>1st / any other floor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MCB_Rating__c.field-meta.xml
<CustomField>
    <fullName>MCB_Rating__c</fullName>
    <label>MCB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Details__c.field-meta.xml
<CustomField>
    <fullName>Site_Details__c</fullName>
    <label>Site Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Built</fullName>
            </value>
            <value>
                <fullName>Ready Built</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Space_for_Machine_movement__c.field-meta.xml
<CustomField>
    <fullName>Space_for_Machine_movement__c</fullName>
    <label>Space for Machine movement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Not Ok</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Steam_Provision__c.field-meta.xml
<CustomField>
    <fullName>Steam_Provision__c</fullName>
    <label>Steam Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Power_Req_Connected_Load__c.field-meta.xml
<CustomField>
    <fullName>Total_Power_Req_Connected_Load__c</fullName>
    <label>Total Power Req.(Connected Load)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Water__c.field-meta.xml
<CustomField>
    <fullName>Water__c</fullName>
    <label>Water</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Water_Hardness__c.field-meta.xml
<CustomField>
    <fullName>Water_Hardness__c</fullName>
    <label>Water Hardness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PreInstallationComCtrlTest.cls
@isTest 
public class PreInstallationComCtrlTest {
    
    @testSetup
    public static void insertOppData(){
        Account acc = TestDataFactory.createAccount();
        acc.Type = 'Upgrade';
        acc.Type_of_Account__c='Key Account';
        acc.Sub_type_of_Account__c='PAN India Presence';
        Update acc;
        
        User userObj = [SELECT Id From User WHERE Id =: UserInfo.getUserId()];
        Opportunity testOpp = TestDataFactory.createOpportunityForAccount(acc.Id,'Prospecting',userObj);
    }
    
    @isTest 
    public static void testParentComponent(){
        Opportunity oppObj = [SELECT Id, Product_category__c From Opportunity Limit 1];
        
        PreInstallationOpportunityController.getProductCategory(oppObj.Id);
        PreInstallationOpportunityController.getProductCategory(null);
    }
    
    @isTest 
    public static void testILMChildComponent(){
        Opportunity oppObj = [SELECT Id, Product_category__c From Opportunity Limit 1];
        oppObj.BOQ_Machine_List__c = 'Yes';
        oppObj.Heating_Type__c = 'Electric';
        oppObj.Laundry_Set_up__c = 'New';
        oppObj.Site_Details__c = 'To be Built';
        oppObj.If_To_be_built_please_share_details__c = 'Construction started';
        oppObj.Clear_Passage_for_Vehicle__c = 'Ok';
        oppObj.Space_for_Machine_movement__c = 'Ok';
        oppObj.Check_Room_Height__c = 'Yes';
        oppObj.Installation_Except_GF_LB__c = 'Yes';
        oppObj.Machine_Installation_Floor_Level__c = 'Lower Basement';
        oppObj.Check_Utility_Connection_Availability__c = 'Yes';
        oppObj.Water__c = 'Yes';
        oppObj.Electrical_Provision__c = 'Yes';
        oppObj.Steam_Provision__c = 'Yes';
        oppObj.Drainage__c = 'Yes';
        oppObj.Air_Line_Provision__c = 'Yes';
        oppObj.Check_Water_Pressure__c = 'Yes';
        oppObj.Check_Water_Hardness__c = 'Yes';
        oppObj.Check_Hot_Air_Exhaust_Provision__c = 'Yes';
        oppObj.Check_Provision_for_Ventilation_in_Room__c = 'Yes';
        System.assertEquals('Electric', oppObj.Heating_Type__c = 'Electric');
        Test.startTest();
        Update oppObj;
        Test.stopTest();
        
        OpportunityILMTableComponentController.getOppRecord(oppObj.Id);
        List<OpportunityILMTableComponentController.wrapperClassChildTable> wrapperObjList = new List<OpportunityILMTableComponentController.wrapperClassChildTable>();
        OpportunityILMTableComponentController.wrapperClassChildTable wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'BOQ_Machine_List__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Heating_Type__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Laundry_Set_up__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Site_Details__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'If_To_be_built_please_share_details__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Clear_Passage_for_Vehicle__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Space_for_Machine_movement__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Room_Height__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Installation_Except_GF_LB__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Machine_Installation_Floor_Level__c';
        wrapperObj.fieldCurrentValue = 'Lower Basement';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Utility_Connection_Availability__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Water__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Electrical_Provision__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Steam_Provision__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Drainage__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Air_Line_Provision__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Water_Pressure__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Water_Hardness__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Hot_Air_Exhaust_Provision__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        wrapperObj = new OpportunityILMTableComponentController.wrapperClassChildTable();
        wrapperObj.fieldApiName = 'Check_Provision_for_Ventilation_in_Room__c';
        wrapperObj.fieldCurrentValue = 'Yes';
        wrapperObjList.add(wrapperObj);
        OpportunityILMTableComponentController.saveRecord(wrapperObjList,oppObj.Id);
        OpportunityILMTableComponentController.getOpportunityId(oppObj.Id);
        OpportunityILMTableComponentController.getOpportunityId(null);
        
    }
    
    @isTest 
    public static void testIDWChildComponent(){
        OpportunityIDWTableComponentController.saveRecord(new Opportunity());
        OpportunityIDWTableComponentController.getOppRecord(null);
        Opportunity oppObj = [SELECT Id, Product_category__c From Opportunity Limit 1];
        oppObj.Machine_Dimensions_w_d_h_Space_Req__c = 'Yes';
        oppObj.Total_Power_Req_Connected_Load__c = 'Yes';
        oppObj.Electric_Connection_Incoming_Supp_Vol__c = 'Yes';
        oppObj.MCB_Rating__c = 'Yes';
        oppObj.Required_Power_Cable_Size_Rating__c = 'Yes';
        oppObj.Water_Hardness__c = 'Yes';
        oppObj.Required_Intel_Water_Pressure__c = 'Yes';
        oppObj.Water_Intel_Size_With_Ball_Value_M_T_S__c = 'Yes';
        oppObj.Drain_Outlet_Size_Gravity_Drain_Req__c = 'Yes';
        oppObj.Model__c = 'Yes';
        Test.startTest();
        Update oppObj;
        Test.stopTest();
        System.assertEquals('Yes', oppObj.MCB_Rating__c, 'Yes');
        OpportunityIDWTableComponentController.getOppRecord(oppObj.Id);
        OpportunityIDWTableComponentController.saveRecord(oppObj);
    }
}