force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greenfield</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/Blue_Sheet__c.object-meta.xml
<CustomObject>
    <label>Blue Sheet Entry</label>
    <nameField>
        <displayFormat>BSN-{000000}</displayFormat>
        <label>Blue Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blue Sheet Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influence_Key_Win_Results__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influence_Key_Win_Results__c</fullName>
    <label>Buying Influence Key Win-Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influence_Name__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influence_Name__c</fullName>
    <formula>Buying_Influences_Involved__r.FirstName +&apos; &apos;+ Buying_Influences_Involved__r.LastName</formula>
    <label>Buying Influence Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influences_Involved__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influences_Involved__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buying Influences Involved</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Blue Sheet Entries</relationshipLabel>
    <relationshipName>Blue_Sheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Degree_Of_Influence__c.field-meta.xml
<CustomField>
    <fullName>Degree_Of_Influence__c</fullName>
    <label>Degree Of Influence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Evidence_to_support_your_Rating__c.field-meta.xml
<CustomField>
    <fullName>Evidence_to_support_your_Rating__c</fullName>
    <label>Evidence to support your Rating</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Ideal_Customer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Customer_Criteria__c</fullName>
    <label>Ideal Customer Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Possible_Actions__c.field-meta.xml
<CustomField>
    <fullName>Possible_Actions__c</fullName>
    <label>Possible Actions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Buying Influences Involved</fullName>
            </value>
            <value>
                <fullName>Evidence to support your Rating</fullName>
            </value>
            <value>
                <fullName>Ideal Customer Criteria</fullName>
            </value>
            <value>
                <fullName>Red Flag</fullName>
            </value>
            <value>
                <fullName>Strength</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adequacy_of_current_position__c.field-meta.xml
<CustomField>
    <fullName>Adequacy_of_current_position__c</fullName>
    <label>Adequacy of current position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUPHORIA</fullName>
            </value>
            <value>
                <fullName>GREAT</fullName>
            </value>
            <value>
                <fullName>SECURE</fullName>
            </value>
            <value>
                <fullName>COMFORT</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>CONCERN</fullName>
            </value>
            <value>
                <fullName>DISCOMFORT</fullName>
            </value>
            <value>
                <fullName>WORRY</fullName>
            </value>
            <value>
                <fullName>FEAR</fullName>
            </value>
            <value>
                <fullName>PANIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Blue_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Blue_Sheet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blue Sheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Blue_Sheet_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Blue_Sheet_Created_Date__c</fullName>
    <label>Blue Sheet Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Blue_Sheet_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Blue_Sheet_Last_Modified_Date__c</fullName>
    <label>Blue Sheet Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competition_Type__c.field-meta.xml
<CustomField>
    <fullName>Competition_Type__c</fullName>
    <label>Competition Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Buying From Someone Else</fullName>
            </value>
            <value>
                <fullName>Using Budget for Something Else</fullName>
            </value>
            <value>
                <fullName>Using Internal Resources</fullName>
            </value>
            <value>
                <fullName>Doing Nothing</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
                <isActive>false</isActive>
                <label>B</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>D</fullName>
                <isActive>false</isActive>
                <label>D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CurrentVolume__c.field-meta.xml
<CustomField>
    <fullName>CurrentVolume__c</fullName>
    <label>Current Volume</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Degree_of_Influence__c.field-meta.xml
<CustomField>
    <fullName>Degree_of_Influence__c</fullName>
    <label>Degree of Influence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ideal_Customer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Customer_Criteria__c</fullName>
    <label>Ideal Customer Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-5</fullName>
                <label>-5 Antagonistic Anti-Sponsor</label>
            </value>
            <value>
                <fullName>-4</fullName>
                <label>-4 Very Negative</label>
            </value>
            <value>
                <fullName>-3</fullName>
                <label>-3 Negative</label>
            </value>
            <value>
                <fullName>-2</fullName>
                <label>-2 Uninterested</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>-1 Probably Won&apos;t Resist</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 Will Go Along</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 Interested</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 Supportive</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 Strongly Supportive</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 Enthusiastic Advocate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/My_Position_vs_Competition__c.field-meta.xml
<CustomField>
    <fullName>My_Position_vs_Competition__c</fullName>
    <label>My Position vs. Competition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Only Alternative</fullName>
            </value>
            <value>
                <fullName>Front Runner</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Zero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Place_in_Sales_Funnel__c.field-meta.xml
<CustomField>
    <fullName>Place_in_Sales_Funnel__c</fullName>
    <label>Place in Sales Funnel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Universe</fullName>
            </value>
            <value>
                <fullName>Above</fullName>
            </value>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Best Few</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Possible_Actions__c.field-meta.xml
<CustomField>
    <fullName>Possible_Actions__c</fullName>
    <label>Possible Actions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <label>Product/Service</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Red_Flags__c.field-meta.xml
<CustomField>
    <fullName>Red_Flags__c</fullName>
    <label>Red Flags</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Person_Involved__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Involved__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Person Involved</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Person_Involved_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Involved_Name__c</fullName>
    <formula>Sales_Person_Involved__r.FirstName +&apos; &apos;+  Sales_Person_Involved__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Person Involved Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesRevenueUnits__c.field-meta.xml
<CustomField>
    <fullName>SalesRevenueUnits__c</fullName>
    <label>Sales Revenue/Units</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Specify_Cometitor_s__c.field-meta.xml
<CustomField>
    <fullName>Specify_Cometitor_s__c</fullName>
    <label>Specify Cometitor(s)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Strengths__c.field-meta.xml
<CustomField>
    <fullName>Strengths__c</fullName>
    <label>Strengths</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Summary_of_Position__c.field-meta.xml
<CustomField>
    <fullName>Summary_of_Position__c</fullName>
    <formula>&quot;Strengths: &quot; &amp; Strengths__c &amp; BR() &amp; &quot;Red Flags: &quot; &amp; Red_Flags__c</formula>
    <label>Summary of Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timing_for_Priorities__c.field-meta.xml
<CustomField>
    <fullName>Timing_for_Priorities__c</fullName>
    <label>Timing for Priorities</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Work it in</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalPotentialVolume__c.field-meta.xml
<CustomField>
    <fullName>TotalPotentialVolume__c</fullName>
    <label>Total Potential Volume</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PDFGenerate.cls
public class PDFGenerate {
    
    public Opportunity opportunity { get; set; }
    public List<Blue_Sheet__c> blueSheets { get; set; }
    
    public PDFGenerate() {
        Id oppId = ApexPages.currentPage().getParameters().get('id');
        if (oppId != null) {
            try {
                opportunity = [SELECT Id, Red_Flags__c, Strengths__c, Sales_Person_Involved__c, CurrentVolume__c, 
                                       TotalPotentialVolume__c, Adequacy_of_current_position__c, SalesRevenueUnits__c, 
                                       Competition_Type__c, My_Position_vs_Competition__c, Place_in_Sales_Funnel__c, 
                                       Timing_for_Priorities__c, Specify_Cometitor_s__c,CloseDate,Amount,
                                       Summary_of_Position__c, Possible_Actions__c , Account.Name, Name, Sales_Person_Involved_Name__c, Blue_Sheet_Last_Modified_Date__c, Blue_Sheet_Created_Date__c,Product_Service__c
                                FROM Opportunity 
                                WHERE Id = :oppId
                                LIMIT 1];
                
                blueSheets = [Select Id, Buying_Influence_Key_Win_Results__c,Buying_Influences_Involved__c,Buying_Influence_Name__c, Degree_Of_Influence__c, Evidence_to_support_your_Rating__c, Ideal_Customer_Criteria__c
                                                 , Match_to_Criteria_5_to_5__c, Mode__c, OpportunityId__c, Rating_5_to_5__c, Role__c,Type__c,Summary_Of_My_Position_Today__c,
                   Possible_Actions__c, What__c, Who__c, flag__c,When__c,Information_Needed__c,From_Whom__c, who_Name__c, Whom_Name__c from Blue_Sheet__c where OpportunityId__c =:oppId Order by createddate asc];
                Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename='+'Bluesheet_'+(opportunity.name).replace(' ','_')+String.valueOf(Date.today()).removeEnd(' 00:00:00')+'.pdf');
            } catch (Exception e) {
                ExceptionHandler.logException('PDFGenerate', 'PDFGenerate', e);
            }
        }
    } 
     public DateTime getBlueSheetCreatedDateIST() {
        return convertToIST(opportunity.Blue_Sheet_Created_Date__c);
    }

    public DateTime getBlueSheetLastModifiedDateIST() {
        return convertToIST(opportunity.Blue_Sheet_Last_Modified_Date__c);
    }

    private DateTime convertToIST(DateTime gmtDateTime) {
        if (gmtDateTime != null) {
            return gmtDateTime.addHours(5).addMinutes(30);
        }
        return null;
    }
}