force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Includes__c.field-meta.xml
<CustomField>
    <fullName>Freight_Includes__c</fullName>
    <label>Freight Included</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Freight_Terms__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Included in the Quote</fullName>
            </value>
            <value>
                <fullName>Extras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Terms__c.field-meta.xml
<CustomField>
    <fullName>Freight_Terms__c</fullName>
    <label>Freight Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borne by IFB</fullName>
                <default>true</default>
                <label>Borne by IFB</label>
            </value>
            <value>
                <fullName>Borne by Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailNotificationOpenQuotesContTest.cls
@isTest 
public class EmailNotificationOpenQuotesContTest {
    
    @testSetup
    public static void EmailNotificationOpenQuotesClass(){
        
        Account account = TestDataFactory.createAccount();
        User userObj = [SELECT Id From User WHERE Id =: UserInfo.getUserId()];
        Opportunity oppoorunity = TestDataFactory.createOpportunityForAccount(account.Id,'Prospecting',userObj);
        SBQQ__Quote__c quote = TestDataFactory.createQuote(oppoorunity);
        quote.Freight_Terms__c = 'Borne by Customer';
        quote.Freight_Includes__c = 'Extras';
        quote.OwnerId = userObj.Id;
        Update quote;
        
        SBQQ__Quote__c quote1 = TestDataFactory.createQuote(oppoorunity);
        quote1.Freight_Terms__c = 'Borne by Customer';
        quote1.Freight_Includes__c = 'Extras';
        quote1.OwnerId = userObj.Id;
        Update quote1;
        
    }
    
    @isTest 
    public static void testopenQuotesReport(){
        Test.startTest();
        List<SBQQ__Quote__c> quoteList = new List<SBQQ__Quote__c>();
        quoteList = [SELECT Id, OwnerId, Freight_Terms__c, Freight_Includes__c From SBQQ__Quote__c];
        EmailNotificationOpenQuotesController.openQuotesReport();  
        EmailNotificationOpenQuotesController.leadDetailMapping(quoteList , new Set<Id>{quoteList[0].OwnerId});
        System.assertEquals(1, Limits.getEmailInvocations(), 'An email should have been sent.');
        Test.stopTest();  
    }    
}