force-app/main/default/objects/Bank_Detail__c/Bank_Detail__c.object-meta.xml
<CustomObject>
    <description>this object is use to store bank details of IFB</description>
    <label>Bank Detail</label>
    <nameField>
        <label>Bank Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bank_Detail__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Detail</label>
    <referenceTo>Bank_Detail__c</referenceTo>
    <relationshipLabel>Custom Quotes</relationshipLabel>
    <relationshipName>Custom_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/BOQ_specified.recordType-meta.xml
<RecordType>
    <fullName>BOQ_specified</fullName>
    <active>true</active>
    <label>BOQ/URS specified</label>
</RecordType>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1040</fullName>
                <label>Bommasandra Factory</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <label>Chennai</label>
            </value>
            <value>
                <fullName>4025</fullName>
                <label>Bangalore</label>
            </value>
            <value>
                <fullName>4043</fullName>
                <label>Hyderabad</label>
            </value>
            <value>
                <fullName>4046</fullName>
                <label>Vijayawada</label>
            </value>
            <value>
                <fullName>4085</fullName>
                <label>Kochin</label>
            </value>
            <value>
                <fullName>5016</fullName>
                <label>Mumbai</label>
            </value>
            <value>
                <fullName>5005</fullName>
                <label>Pune</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <label>Ahmedabad</label>
            </value>
            <value>
                <fullName>5030</fullName>
                <label>Goa</label>
            </value>
            <value>
                <fullName>2011</fullName>
                <label>Bhopal</label>
            </value>
            <value>
                <fullName>5024</fullName>
                <label>Raipur</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <label>Delhi</label>
            </value>
            <value>
                <fullName>2021</fullName>
                <label>Lucknow</label>
            </value>
            <value>
                <fullName>2025</fullName>
                <label>Ghaziabad</label>
            </value>
            <value>
                <fullName>2005</fullName>
                <label>Jaipur</label>
            </value>
            <value>
                <fullName>2054</fullName>
                <label>Mohali</label>
            </value>
            <value>
                <fullName>2050</fullName>
                <label>Ludhiana</label>
            </value>
            <value>
                <fullName>3000</fullName>
                <label>Kolkata</label>
            </value>
            <value>
                <fullName>3020</fullName>
                <label>JAMSHEDPUR MARKETING BRANCH</label>
            </value>
            <value>
                <fullName>3030</fullName>
                <label>Bhubaneswar</label>
            </value>
            <value>
                <fullName>3040</fullName>
                <label>Guwahati</label>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>3035</fullName>
                <label>PATNA MARKETING BRANCH</label>
            </value>
            <value>
                <fullName>3535</fullName>
                <label>PATNA SERVICE BRANCH</label>
            </value>
            <value>
                <fullName>3520</fullName>
                <label>JAMSHEDPUR SERVICE BRANCH</label>
            </value>
            <value>
                <fullName>JAMSHEDPUR MARKETING BRANCH</fullName>
                <isActive>false</isActive>
                <label>JAMSHEDPUR MARKETING BRANCH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConfigureQuoteTest.cls
@isTest
public class ConfigureQuoteTest {
    
    @testSetup
    public static void dataSetup(){
        Account insertedAcc = TestDataFactory.createAccount();
        Product2 prodObj = TestDataFactory.createProduct2();
        User objUser = [SELECT Id From User WHERE Id =: UserInfo.getUserId()];
        Opportunity opp = TestDataFactory.createOpportunity(' test 1 ','Qualification',System.today().addDays(5),'ILM','Electric');
        Id priceBookEntityIdNew = TestDataFactory.createPricebookEntry(prodObj.Id);
        TestDataFactory.createOppLineItem(opp.Id,priceBookEntityIdNew,opp.StageName);
        SBQQ__Quote__c quote = TestDataFactory.createQuote(opp);
        TestDataFactory.createQuoteLine(quote.Id,false,1,prodObj.Id);
        Bank_Detail__c bankDetail = new Bank_Detail__c();
        bankDetail.Name= 'Test Bank';
        bankDetail.Branch__c = 'test Branch';
        bankDetail.Address__c = '3b/3c, Ifb Industries Ltd, Bommasandra Industrial Area, Anekal Taluk,';
        insert bankDetail;
    }
    
    @isTest
    public static void quoteEditLinesTest(){
        
        //Opportunity opp1 = TestDataFactory.createOpportunityForAccount(insertedAcc.Id,'Qualification',objUser);
        Opportunity opp = [SELECT Id, StageName From Opportunity Limit 1];
        SBQQ__Quote__c quote = [SELECT Id From SBQQ__Quote__c Limit 1];
        
        
        ConfigureQuote.FlowInputs flowInputClassObj = new ConfigureQuote.FlowInputs();
        flowInputClassObj.opportunityId = opp.Id;
        flowInputClassObj.CostEditable = true;
        flowInputClassObj.quoteId = quote.Id;
        flowInputClassObj.DeveloperName = 'BOQ_specified';
        try{
        List<ConfigureQuote.FlowOutputs> getDataList = ConfigureQuote.quoteEditLines(new List<ConfigureQuote.FlowInputs>{flowInputClassObj});
            System.assertEquals(1 , getDataList.size(), 'List Should Be Not Empty...');
            
            
        }catch(AuraHandledException exp){
            
        }
        
        try{
        ConfigureQuote.quoteEditLines(new List<ConfigureQuote.FlowInputs>());
        }catch(AuraHandledException exp){
            
        }
                
        ConfigureQuote.FlowInputs flowInputClassObj1 = new ConfigureQuote.FlowInputs();
        flowInputClassObj1.quoteId = quote.Id;
        flowInputClassObj1.PriceEditable = true;
        flowInputClassObj1.CostEditable = false;
        flowInputClassObj1.CurrencyISO = 'test';
        
        ConfigureQuote.FlowOutputs flowOutputObjNew = new ConfigureQuote.FlowOutputs();
		flowOutputObjNew.quoteId = quote.Id;     
    }
    
}