force-app/main/default/objects/Lead/fields/Call_Centre_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Call_Centre_Remarks__c</fullName>
    <label>Call Centre Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmployeeID__c.field-meta.xml
<CustomField>
    <fullName>EmployeeID__c</fullName>
    <label>Employee Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EmployeeName__c</fullName>
    <label>Employee Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC Dealer</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Backend Team</fullName>
            </value>
            <value>
                <fullName>Branch Sales Manager</fullName>
            </value>
            <value>
                <fullName>Branch Service Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Constructors - Building Constructors</fullName>
            </value>
            <value>
                <fullName>Constructors - Canteen Constructors</fullName>
            </value>
            <value>
                <fullName>Constructors - Laundry Constructors</fullName>
            </value>
            <value>
                <fullName>Constructors - MES Constructors</fullName>
            </value>
            <value>
                <fullName>Consultant - Architech/PMC Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Design Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Kitchen Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Laundry Consultant</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CSR</fullName>
            </value>
            <value>
                <fullName>Dealers - Kitchen equipment supplier</fullName>
            </value>
            <value>
                <fullName>Dealers - Medical equipment supplier</fullName>
            </value>
            <value>
                <fullName>Dealers - Other equipment supplier</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Domestic Dealers</fullName>
            </value>
            <value>
                <fullName>Domestic Distributors</fullName>
            </value>
            <value>
                <fullName>DSO Service Engineer</fullName>
            </value>
            <value>
                <fullName>Facility Management Companies</fullName>
            </value>
            <value>
                <fullName>Field Team</fullName>
            </value>
            <value>
                <fullName>Foreigners</fullName>
            </value>
            <value>
                <fullName>Franchisee Owner</fullName>
            </value>
            <value>
                <fullName>Institutional dealers</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Regional Sales Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>ILE</fullName>
                <isActive>false</isActive>
                <label>ILE</label>
            </value>
            <value>
                <fullName>Industrial Dishwasher</fullName>
                <isActive>false</isActive>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Industrial Laundry Machine</fullName>
                <isActive>false</isActive>
                <label>Industrial Laundry Machine</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Customer__c</fullName>
    <label>Type of Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Domestic</fullName>
                <isActive>false</isActive>
                <label>Domestic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadControllerTest.cls
@isTest
public class LeadControllerTest {
    @isTest
    static void testCreateLead() {
        String leadDataJson = '{"Type_of_Customer__c":"Existing","Phone":"9827182781","Operation_Parakram__c":"Yes","Next_Follow_up_Date_Time__c":"2025-02-20","FirstName":"ffff","LastName":"sssss","Email":"warpdrivetechworks.blinfcon392@biocon.com","Company":"final","Street":"sasa","City":"Jaipur","State":"Rajasthan","PostalCode":"303303","Country":"India","Shipping__Street__s": "ssss","Shipping__City__s":"Trichy","Shipping__PostalCode__s":"123","Description":"aa","EmployeeName__c":"Neethu","EmployeeID__c":"123","Call_Centre_Remarks__c":"abcd","accountType":"customer","Product_Category__c":"Industrial Laundry Machine","IsSameLocation":true,"callCenterTeam":"Domestic Call Centre Team"}';
        String leadDataJson1 = '{"Type_of_Customer__c":"Existing","LeadSource":"Industrial Service Team","Partner_Email__c":"test@mail.com","Lead_Sub_Source__c":"Backend Team","LastName":"sssss","Email":"test@example.com","Company":"final","Street":"sasa","City":"Jaipur","State":"Rajasthan","PostalCode":"303303","Country":"India","Shipping__StateCode__s":"Tamil Nadu","Shipping__CountryCode__s":"India","Shipping__Street__s": "ssss","Shipping__City__s":"Trichy","Shipping__PostalCode__s":"12345","Description":"aa","EmployeeName__c":"Neethu","EmployeeID__c":"123","Call_Centre_Remarks__c":"abcd","accountType":"Partners"}';
        String leadDataJson2 = '{"Type_of_Customer__c":"Existing","FirstName":"ffff","LastName":"sssss","Email":"warpdrivetechworks.blinfcon392@biocon.com","Company":"final","Street":"sasa","City":"Jaipur","State":"Rajasthan","PostalCode":"303303","Country":"India","Shipping__Street__s": "ssss","Shipping__City__s":"Trichy","Shipping__PostalCode__s":"123","Description":"aa","EmployeeName__c":"Neethu","EmployeeID__c":"123","Call_Centre_Remarks__c":"abcd","accountType":"callCenterTeam","Product_Category__c":"Industrial Laundry Machine","IsSameLocation":true,"callCenterTeam":"Domestic Call Centre Team"}';
        
        // Call the method being tested
        try{
            Test.startTest();
            String leadId = LeadController.createLead(leadDataJson);
            String leadId1 = LeadController.createLead(leadDataJson1);
            String leadId2 = LeadController.createLead(leadDataJson2);
            
            Test.stopTest();
        }catch(exception e){
            
        }
        
        
        
    }
    
    @isTest
    static void testDuplicateLeads(){
        Lead leadRecords = TestDataFactory.createTestLead('Test Company2', '123452', 'GoogleAds', 'Domestic', 'IDW', 'Washing','123452',false);
        Test.startTest();
        List<Lead> leadList = LeadController.leadDuplicateCheck('Test Company','ILM','680030');
        Test.stopTest();
    }
    
    @isTest
    static void testLeadDuplicateCheck() {
        try{
            Lead testLead = new Lead(
                LastName = 'Test',
                Company = 'TestCompany',
                Product_Category__c = 'ILM',
                PostalCode = '680030',
                Email = 'test@example.com'
            );
            insert testLead;
            Lead testLead2 = new Lead(
                LastName = 'Test',
                Company = 'TestCompnay',
                Product_Category__c = 'ILM',
                PostalCode = '680030',
                Email = 'test2@example.com'
            );
            User uhs = [select Id from User where Profile.UserLicense.Name = 'Guest User License' limit 1];
            System.runAs(uhs) {
                Test.startTest();
                insert testLead2;
                
                Test.stopTest();
            }	
        }catch(exception e){
            
        }             
        List<Lead> duplicateLeads = LeadController.leadDuplicateCheck('TestCompany', 'ILM', '680030');
        
    }
    
}