force-app/main/default/objects/Lead/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>ILE</fullName>
                <isActive>false</isActive>
                <label>ILE</label>
            </value>
            <value>
                <fullName>Industrial Dishwasher</fullName>
                <isActive>false</isActive>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Industrial Laundry Machine</fullName>
                <isActive>false</isActive>
                <label>Industrial Laundry Machine</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Capacity_Practical_Basket__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Practical_Basket__c</fullName>
    <label>Capacity ( Practical ) Baskets/Hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Choice_35__c.field-meta.xml
<CustomField>
    <fullName>Choice_35__c</fullName>
    <label>Choice 35</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Not OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Choice_40__c.field-meta.xml
<CustomField>
    <fullName>Choice_40__c</fullName>
    <label>Choice 40</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Not OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Choice_50__c.field-meta.xml
<CustomField>
    <fullName>Choice_50__c</fullName>
    <label>Choice 50</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Not OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Choice_60__c.field-meta.xml
<CustomField>
    <fullName>Choice_60__c</fullName>
    <label>Choice 60</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Not Ok</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Continuous_load__c.field-meta.xml
<CustomField>
    <fullName>Continuous_load__c</fullName>
    <label>Continuous load</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Entry_side__c.field-meta.xml
<CustomField>
    <fullName>Entry_side__c</fullName>
    <label>Entry Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Heating_Type__c.field-meta.xml
<CustomField>
    <fullName>Heating_Type__c</fullName>
    <label>Heating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Dual (Electric &amp; Steam)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industrial_Dishwasher_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Industrial_Dishwasher_Product_Type__c</fullName>
    <label>Industrial Dishwasher Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Plate</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_height_of_washable_Glasses__c.field-meta.xml
<CustomField>
    <fullName>Max_height_of_washable_Glasses__c</fullName>
    <label>Glass Height in CM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_height_of_washable_Plate__c.field-meta.xml
<CustomField>
    <fullName>Max_height_of_washable_Plate__c</fullName>
    <label>Max Height of Washable Plates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/No_of_Double_bed_Sheets_hr__c.field-meta.xml
<CustomField>
    <fullName>No_of_Double_bed_Sheets_hr__c</fullName>
    <label>No. of Double bed Sheets/hr</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/No_of_Plate_wash_up_to_12__c.field-meta.xml
<CustomField>
    <fullName>No_of_Plate_wash_up_to_12__c</fullName>
    <label>No of Plates Washed up to 12</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/No_of_Plate_wash_up_to_18_Pocket_type_p__c.field-meta.xml
<CustomField>
    <fullName>No_of_Plate_wash_up_to_18_Pocket_type_p__c</fullName>
    <label>No of Plates wash up to 18</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/No_of_plates_per_basket__c.field-meta.xml
<CustomField>
    <fullName>No_of_plates_per_basket__c</fullName>
    <label>No. of plates per basket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/No_of_Single_sheets_hr__c.field-meta.xml
<CustomField>
    <fullName>No_of_Single_sheets_hr__c</fullName>
    <label>No. of Single sheets / hr</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Out_Put_Capacity_Max_Racks__c.field-meta.xml
<CustomField>
    <fullName>Out_Put_Capacity_Max_Racks__c</fullName>
    <label>Output Capacity ( Max) Racks/Hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plate_Diameter_Width_of_plate_in_cm__c.field-meta.xml
<CustomField>
    <fullName>Plate_Diameter_Width_of_plate_in_cm__c</fullName>
    <label>Plate Diameter /Width of plate in cm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Load_per_cycle__c.field-meta.xml
<CustomField>
    <fullName>Total_Load_per_cycle__c</fullName>
    <label>Total Load per Cycle for Wash only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Load_per_Cycle_for__c.field-meta.xml
<CustomField>
    <fullName>Total_Load_per_Cycle_for__c</fullName>
    <label>Total no. of ironing sheet  per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Load_per_Cycle_for_Dry_Load__c.field-meta.xml
<CustomField>
    <fullName>Total_Load_per_Cycle_for_Dry_Load__c</fullName>
    <label>Total Load per Cycle for Dry Load</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Power_Req_Connected_Load__c.field-meta.xml
<CustomField>
    <fullName>Total_Power_Req_Connected_Load__c</fullName>
    <label>Total Power Req.(Connected Load)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Dry_load_capacity__c.field-meta.xml
<CustomField>
    <fullName>Dry_load_capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Dry load capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Heating_type__c.field-meta.xml
<CustomField>
    <fullName>Heating_type__c</fullName>
    <label>Heating type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Dual (Electric &amp; Steam)</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Iron_Load_capacity__c.field-meta.xml
<CustomField>
    <fullName>Iron_Load_capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Iron Load capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Height_Of_Washable_Glasses__c.field-meta.xml
<CustomField>
    <fullName>Max_Height_Of_Washable_Glasses__c</fullName>
    <label>Max Height Of Washable Glasses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Height_Of_Washable_Plate__c.field-meta.xml
<CustomField>
    <fullName>Max_Height_Of_Washable_Plate__c</fullName>
    <label>Max Height Of Washable Plate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/No_of_Plate_wash_up_to_12__c.field-meta.xml
<CustomField>
    <fullName>No_of_Plate_wash_up_to_12__c</fullName>
    <label>No of Plate wash up to 12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Shelf_Life_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Shelf_Life_in_Days__c</fullName>
    <label>Shelf Life in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Wash_Load_capacity__c.field-meta.xml
<CustomField>
    <fullName>Wash_Load_capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wash Load capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTest.cls
@isTest
public class OpportunityLineItemTest {
    @isTest
    static void setupTestData() {
        Id pricebookId = Test.getStandardPricebookId();
        
        Pricebook2 ilmPricebook = new Pricebook2(Name = 'Industrial Washing Machine', IsActive = true);
        Pricebook2 idwPricebook = new Pricebook2(Name = 'Industrial Dishwasher', IsActive = true);
        
        insert new List<Pricebook2>{ilmPricebook, idwPricebook};
            
            // Create Products and related Pricebook Entries
            Product2 product1 = new Product2(Name = 'Washer', Wash_Load_capacity__c = 10, Iron_Load_capacity__c = 60, Dry_load_capacity__c = 60, IsActive = true, Family = 'ILM Products', Heating_Type__c = 'Electric', Shelf_Life_in_Days__c = 20);
        Product2 product2 = new Product2(Name = 'Dryer', Wash_Load_capacity__c = 8, Iron_Load_capacity__c = 120, Dry_load_capacity__c = 120, IsActive = true, Family = 'ILM Products', Heating_Type__c = 'Gas', Shelf_Life_in_Days__c = 30);
        
        insert new List<Product2>{product1, product2};
            
            PricebookEntry pbe1 = new PricebookEntry(Product2Id = product1.Id, Pricebook2Id = pricebookId, UnitPrice = 1000, IsActive = true);
        PricebookEntry pbe2 = new PricebookEntry(Product2Id = product2.Id, Pricebook2Id = pricebookId, UnitPrice = 1500, IsActive = true);
        PricebookEntry pbe3 = new PricebookEntry(Product2Id = product1.Id, Pricebook2Id = ilmPricebook.Id, UnitPrice = 1100, IsActive = true);
        PricebookEntry pbe4 = new PricebookEntry(Product2Id = product2.Id, Pricebook2Id = idwPricebook.Id, UnitPrice = 1200, IsActive = true);
        
        insert new List<PricebookEntry>{pbe1, pbe2, pbe3, pbe4};
            
            // Create Opportunities
            Opportunity opp1 = new Opportunity(Name = 'Test Opp 1', Pricebook2Id=ilmPricebook.Id, StageName = 'Qualification', Heating_Type__c='Electric',LeadSource='Direct Lead', 
                                               CloseDate = Date.today().addDays(10), Product_category__c = 'ILM', Max_height_of_washable_Glasses__c = 15, Max_height_of_washable_Plate__c = 12,
                                               Out_Put_Capacity_Max_Racks__c = 10,  No_of_Plate_wash_up_to_12__c = 6, No_of_Plate_wash_up_to_18_Pocket_type_p__c = 4,
                                               Total_Load_per_Cycle_for_Dry_Load__c = 36,Size__c=1.7, Total_Load_per_Cycle_for__c = 70,Capacity_Practical_Basket__c=900, Total_Load_per_cycle__c = 300,No_of_Double_bed_Sheets_hr__c= 180,No_of_Single_sheets_hr__c=90,
                                               Total_Power_Req_Connected_Load__c = 'NO', CurrencyIsoCode = 'INR');
        
        Opportunity opp4 = new Opportunity(Name = 'Test Opp 1', Pricebook2Id=ilmPricebook.Id, StageName = 'Proposal/Price Quote', Heating_Type__c='Steam',LeadSource ='Direct Lead', 
                                           CloseDate = Date.today().addDays(10), Product_category__c = 'ILM', Max_height_of_washable_Glasses__c = 15, Max_height_of_washable_Plate__c = 12,
                                           Out_Put_Capacity_Max_Racks__c = 10,  No_of_Plate_wash_up_to_12__c = 6, No_of_Plate_wash_up_to_18_Pocket_type_p__c = 4,
                                           Total_Load_per_Cycle_for_Dry_Load__c = 20,Size__c=1.7, Total_Load_per_Cycle_for__c = 300,Capacity_Practical_Basket__c=900, Total_Load_per_cycle__c = 80,No_of_Double_bed_Sheets_hr__c= 180,
                                           Total_Power_Req_Connected_Load__c = 'NO', CurrencyIsoCode = 'INR');
        
        Opportunity opp5 = new Opportunity(Name = 'Test Opp 5', Pricebook2Id=ilmPricebook.Id, StageName = 'Load Calculation', Heating_Type__c='Steam',LeadSource ='Direct Lead', 
                                           CloseDate = Date.today().addDays(10), Product_category__c = 'ILM', Max_height_of_washable_Glasses__c = 10, Max_height_of_washable_Plate__c = 12,
                                           Out_Put_Capacity_Max_Racks__c = 10,  No_of_Plate_wash_up_to_12__c = 6, No_of_Plate_wash_up_to_18_Pocket_type_p__c = 4,
                                           Total_Load_per_Cycle_for_Dry_Load__c = 300,Size__c=1.5, Total_Load_per_Cycle_for__c = 300,Capacity_Practical_Basket__c=900, Total_Load_per_cycle__c = 300,No_of_Single_sheets_hr__c=90,
                                           Total_Power_Req_Connected_Load__c = 'NO', CurrencyIsoCode = 'INR');
        
        Opportunity opp2 = new Opportunity(Name = 'Test Opp 2', Pricebook2Id=idwPricebook.Id,
                                           StageName = 'Qualification', Entry_side__c='Left',CloseDate = Date.today().addDays(10), Product_category__c = 'IDW',LeadSource ='Direct Lead',
                                           Max_height_of_washable_Glasses__c = 10,Choice_35__c = 'OK',Choice_40__c='OK' ,Choice_50__c='OK',Choice_60__c='OK',Max_height_of_washable_Plate__c = 8,No_of_plates_per_basket__c='18', Capacity_Practical_Basket__c = 7,
                                           Plate_Diameter_Width_of_plate_in_cm__c=10, Industrial_Dishwasher_Product_Type__c = 'Glass', Total_Power_Req_Connected_Load__c = 'NO',Continuous_load__c='No', CurrencyIsoCode = 'INR');
        Opportunity opp3 = new Opportunity( Name = 'Test Opp 2', Pricebook2Id=idwPricebook.Id,
                                           StageName = 'Load Calculation', Entry_side__c='Left',CloseDate = Date.today().addDays(10), Product_category__c = 'IDW',LeadSource ='Direct Lead',
                                           Max_height_of_washable_Glasses__c = 10,Choice_35__c = 'OK',Choice_40__c='OK' ,Choice_50__c='OK',Choice_60__c='OK',Max_height_of_washable_Plate__c = 8,No_of_plates_per_basket__c='18', Capacity_Practical_Basket__c = 7,
                                           Plate_Diameter_Width_of_plate_in_cm__c=10, Industrial_Dishwasher_Product_Type__c = 'Glass', Total_Power_Req_Connected_Load__c = 'NO',Continuous_load__c='Yes', CurrencyIsoCode = 'INR');
        
        Opportunity opp6 = new Opportunity( Name = 'Test Opp 6', Pricebook2Id=idwPricebook.Id,
                                           StageName = 'Proposal/Price Quote', Entry_side__c='Left',LeadSource  ='Direct Lead',
                                           CloseDate = Date.today().addDays(10), Product_category__c = 'IDW',No_of_plates_per_basket__c='9',
                                           Max_height_of_washable_Glasses__c = 10,Choice_35__c = 'Not ok',Choice_40__c='Not ok' ,Choice_50__c='OK',Choice_60__c='OK',Max_height_of_washable_Plate__c = 8, Capacity_Practical_Basket__c = 7,
                                           Plate_Diameter_Width_of_plate_in_cm__c=10, Industrial_Dishwasher_Product_Type__c = 'Plate', Total_Power_Req_Connected_Load__c = 'Yes',Continuous_load__c='No', CurrencyIsoCode = 'INR');
        
        insert new List<Opportunity>{opp1, opp2,opp3,opp4,opp5,opp6};
            
            // Create Opportunity Line Items
            
            OpportunityLineItem oli3 = new OpportunityLineItem(OpportunityId = opp1.Id, Quantity = 2, PricebookEntryId = pbe3.Id, UnitPrice = 1100);
        OpportunityLineItem oli4 = new OpportunityLineItem(OpportunityId = opp2.Id, Quantity = 1, PricebookEntryId = pbe4.Id, UnitPrice = 1200);
        OpportunityLineItem oli7 = new OpportunityLineItem(OpportunityId = opp5.Id, Quantity = 2, PricebookEntryId = pbe3.Id, UnitPrice = 1200);
        OpportunityLineItem oli5 = new OpportunityLineItem(OpportunityId = opp3.Id, Quantity = 2, PricebookEntryId = pbe4.Id, UnitPrice = 1500);
        OpportunityLineItem oli6 = new OpportunityLineItem(OpportunityId = opp4.Id, Quantity = 2, PricebookEntryId = pbe3.Id, UnitPrice = 1500);
        
        
        insert new List<OpportunityLineItem>{oli3, oli4,oli5,oli6,oli7};
        update oli3;
        delete oli3;
    }
    
}