force-app/main/default/objects/Blue_Sheet__c/Blue_Sheet__c.object-meta.xml
<CustomObject>
    <label>Blue Sheet Entry</label>
    <nameField>
        <displayFormat>BSN-{000000}</displayFormat>
        <label>Blue Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blue Sheet Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influence_Key_Win_Results__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influence_Key_Win_Results__c</fullName>
    <label>Buying Influence Key Win-Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influence_Name__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influence_Name__c</fullName>
    <formula>Buying_Influences_Involved__r.FirstName +&apos; &apos;+ Buying_Influences_Involved__r.LastName</formula>
    <label>Buying Influence Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Buying_Influences_Involved__c.field-meta.xml
<CustomField>
    <fullName>Buying_Influences_Involved__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buying Influences Involved</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Blue Sheet Entries</relationshipLabel>
    <relationshipName>Blue_Sheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Degree_Of_Influence__c.field-meta.xml
<CustomField>
    <fullName>Degree_Of_Influence__c</fullName>
    <label>Degree Of Influence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Evidence_to_support_your_Rating__c.field-meta.xml
<CustomField>
    <fullName>Evidence_to_support_your_Rating__c</fullName>
    <label>Evidence to support your Rating</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red Flag</fullName>
            </value>
            <value>
                <fullName>Strength</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/From_Whom__c.field-meta.xml
<CustomField>
    <fullName>From_Whom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Whom</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blue_Sheet_Entries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Ideal_Customer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Customer_Criteria__c</fullName>
    <label>Ideal Customer Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Information_Needed__c.field-meta.xml
<CustomField>
    <fullName>Information_Needed__c</fullName>
    <label>Information Needed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Match_to_Criteria_5_to_5__c.field-meta.xml
<CustomField>
    <fullName>Match_to_Criteria_5_to_5__c</fullName>
    <label>Match to Criteria (+5 to -5)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+5</fullName>
            </value>
            <value>
                <fullName>+4</fullName>
            </value>
            <value>
                <fullName>+3</fullName>
            </value>
            <value>
                <fullName>+2</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>-2</fullName>
            </value>
            <value>
                <fullName>-3</fullName>
            </value>
            <value>
                <fullName>-4</fullName>
            </value>
            <value>
                <fullName>-5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Trouble</fullName>
            </value>
            <value>
                <fullName>Even Keel</fullName>
            </value>
            <value>
                <fullName>Overconfident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Blue_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Possible_Actions__c.field-meta.xml
<CustomField>
    <fullName>Possible_Actions__c</fullName>
    <label>Possible Actions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Rating_5_to_5__c.field-meta.xml
<CustomField>
    <fullName>Rating_5_to_5__c</fullName>
    <label>Rating (-5 to +5)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+5</fullName>
            </value>
            <value>
                <fullName>+4</fullName>
            </value>
            <value>
                <fullName>+3</fullName>
            </value>
            <value>
                <fullName>+2</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>-2</fullName>
            </value>
            <value>
                <fullName>-3</fullName>
            </value>
            <value>
                <fullName>-4</fullName>
            </value>
            <value>
                <fullName>-5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Economic Buying Influence</fullName>
            </value>
            <value>
                <fullName>User Buying Influence</fullName>
            </value>
            <value>
                <fullName>Technical Buying Influence</fullName>
            </value>
            <value>
                <fullName>Coach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Summary_Of_My_Position_Today__c.field-meta.xml
<CustomField>
    <fullName>Summary_Of_My_Position_Today__c</fullName>
    <label>Summary Of My Position Today</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Buying Influences Involved</fullName>
            </value>
            <value>
                <fullName>Evidence to support your Rating</fullName>
            </value>
            <value>
                <fullName>Ideal Customer Criteria</fullName>
            </value>
            <value>
                <fullName>Red Flag</fullName>
            </value>
            <value>
                <fullName>Strength</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/What__c.field-meta.xml
<CustomField>
    <fullName>What__c</fullName>
    <label>What</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blue_Sheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blue_Sheet__c/fields/who_Name__c.field-meta.xml
<CustomField>
    <fullName>who_Name__c</fullName>
    <formula>Who__r.FirstName +&apos; &apos;+ Who__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>who Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Blue_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Blue_Sheet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blue Sheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Degree_of_Influence__c.field-meta.xml
<CustomField>
    <fullName>Degree_of_Influence__c</fullName>
    <label>Degree of Influence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ideal_Customer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Customer_Criteria__c</fullName>
    <label>Ideal Customer Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-5</fullName>
                <label>-5 Antagonistic Anti-Sponsor</label>
            </value>
            <value>
                <fullName>-4</fullName>
                <label>-4 Very Negative</label>
            </value>
            <value>
                <fullName>-3</fullName>
                <label>-3 Negative</label>
            </value>
            <value>
                <fullName>-2</fullName>
                <label>-2 Uninterested</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <label>-1 Probably Won&apos;t Resist</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 Will Go Along</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 Interested</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 Supportive</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 Strongly Supportive</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 Enthusiastic Advocate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Trouble</fullName>
            </value>
            <value>
                <fullName>Even Keel</fullName>
            </value>
            <value>
                <fullName>Overconfident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Possible_Actions__c.field-meta.xml
<CustomField>
    <fullName>Possible_Actions__c</fullName>
    <label>Possible Actions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Economic Buying Influence</fullName>
            </value>
            <value>
                <fullName>User Buying Influence</fullName>
            </value>
            <value>
                <fullName>Technical Buying Influence</fullName>
            </value>
            <value>
                <fullName>Coach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/What__c.field-meta.xml
<CustomField>
    <fullName>What__c</fullName>
    <label>What</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Who_Name__c.field-meta.xml
<CustomField>
    <fullName>Who_Name__c</fullName>
    <formula>Who__r.FirstName +&apos; &apos;+  Who__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Who Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/blueSheetController.cls
public with sharing class blueSheetController {
    
    @AuraEnabled
    public static void saveblueSheetData(String payload) {
        try{
            Map<String, Object> payloadMap;
            try {
                payloadMap = (Map<String, Object>) JSON.deserializeUntyped(payload);
            } catch (Exception e) {
                throw new AuraHandledException('Error deserializing payload: ' + e.getMessage());
            }
            
            String opportunityId = (String) payloadMap.get('opportunityId');
            if (opportunityId == null) {
                throw new AuraHandledException('Opportunity ID is missing in the payload.');
            }
            
            List<BuyingInfluence> buyingInfluenceList = new List<BuyingInfluence>();
            List<IdealCustomer> idealCustomerList = new List<IdealCustomer>();
            List<Strength> strengthList = new List<Strength>();
            List<RedFlag> redFlagList = new List<RedFlag>();
            
            String buyingInfluenceJson = (String) payloadMap.get('buyingInfluenceList');
            String idealCustomerJson = (String) payloadMap.get('idealCustomerList');
            String strengthJson = (String) payloadMap.get('strengthList');
            String refFlagJson = (String) payloadMap.get('redFlagList');
            
            if (buyingInfluenceJson != null) {
                try {
                    buyingInfluenceList = (List<BuyingInfluence>) JSON.deserialize(buyingInfluenceJson, List<BuyingInfluence>.class);
                } catch (Exception e) {
                    throw new AuraHandledException('Error deserializing buyingInfluenceList: ' + e.getMessage());
                }
            }
            
            if (idealCustomerJson != null) {
                try {
                    idealCustomerList = (List<IdealCustomer>) JSON.deserialize(idealCustomerJson, List<IdealCustomer>.class);
                } catch (Exception e) {
                    throw new AuraHandledException('Error deserializing idealCustomerList: ' + e.getMessage());
                }
            }
            
            if (strengthJson != null) {
                try {
                    strengthList = (List<Strength>) JSON.deserialize(strengthJson, List<Strength>.class);
                } catch (Exception e) {
                    throw new AuraHandledException('Error deserializing idealCustomerList: ' + e.getMessage());
                }
            }
            if (refFlagJson != null) {
                try {
                    redFlagList = (List<RedFlag>) JSON.deserialize(refFlagJson, List<RedFlag>.class);
                } catch (Exception e) {
                    throw new AuraHandledException('Error deserializing idealCustomerList: ' + e.getMessage());
                }
            }
            // Get existing records for the given opportunityId
            Map<String, Blue_Sheet__c> existingRecords = new Map<String, Blue_Sheet__c>();
            
            for (Blue_Sheet__c bs : [
                SELECT Id, OpportunityId__c,Buying_Influences_Involved__c, Evidence_to_support_your_Rating__c, Ideal_Customer_Criteria__c
                FROM Blue_Sheet__c
                WHERE OpportunityId__c = :opportunityId
            ]) {
                existingRecords.put(bs.Id, bs);
            }
            List<Blue_Sheet__c> recordsToUpsert= new List<Blue_Sheet__c>();
            Set<String> idsToDelete = new Set<String>();
            for (BuyingInfluence bi : buyingInfluenceList) {
                if (bi != null) {
                    Blue_Sheet__c newRecord = new Blue_Sheet__c();
                    newRecord.OpportunityId__c = opportunityId;
                    newRecord.Type__c = bi.type;
                    
                    if(bi.buyingInfluences != ''){
                        newRecord.Buying_Influences_Involved__c = bi.buyingInfluences;
                    }
                    newRecord.Role__c = bi.role;
                    newRecord.Degree_Of_Influence__c = bi.degreeOfInfluence;
                    newRecord.Mode__c = bi.mode;
                    newRecord.Buying_Influence_Key_Win_Results__c = bi.winResult;
                    newRecord.Evidence_to_support_your_Rating__c = bi.evidence;
                    newRecord.Rating_5_to_5__c = bi.rating;
                    newRecord.Flag__c = bi.flag;
                    if(existingRecords.containsKey(bi.recId)){
                        newRecord.id = bi.recId;
                        recordsToUpsert.add(newRecord);
                    }else{
                        recordsToUpsert.add(newRecord);
                    }
                }
            }
           
            for (IdealCustomer ic : idealCustomerList) {
                if (ic != null) {
                    Blue_Sheet__c newRecord = new Blue_Sheet__c();
                    newRecord.OpportunityId__c = opportunityId;
                    newRecord.Type__c = ic.type;
                    newRecord.Ideal_Customer_Criteria__c = ic.idealCustomerCriteria;
                    newRecord.Match_to_Criteria_5_to_5__c = ic.matchCriteria;
                    newRecord.Flag__c = ic.flag;
                    if(existingRecords.containsKey(ic.recId)){
                        newRecord.id = ic.recId;
                        recordsToUpsert.add(newRecord);
                    }else{
                        recordsToUpsert.add(newRecord);
                    }
                }
            }
            for (Strength rec : strengthList) {
                if (rec != null) {
                    Blue_Sheet__c newRecord = new Blue_Sheet__c();
                    newRecord.OpportunityId__c = opportunityId;
                    newRecord.Type__c = rec.type;
                    newRecord.Summary_Of_My_Position_Today__c = rec.summryOfMyPosition;
                    newRecord.Possible_Actions__c = rec.possibleActions;
                    newRecord.What__c = rec.what;
                    if(rec.who != ''){
                        newRecord.Who__c = rec.who;
                    }
                    if(rec.whenDate != ''){
                        newRecord.When__c = Date.valueOf(rec.whenDate);
                    }
                    
                    if(existingRecords.containsKey(rec.recId)){
                        newRecord.id = rec.recId;
                        recordsToUpsert.add(newRecord);
                    }else{
                        recordsToUpsert.add(newRecord);
                    }
                }
            }
            for (RedFlag rec : redFlagList) {
                if (rec != null) {
                    Blue_Sheet__c newRecord = new Blue_Sheet__c();
                    newRecord.OpportunityId__c = opportunityId;
                    newRecord.Type__c = rec.type;
                    newRecord.Summary_Of_My_Position_Today__c = rec.summryOfMyPosition;
                    newRecord.Possible_Actions__c = rec.possibleActions;
                    newRecord.Information_Needed__c = rec.informationNeeded;
                    if(rec.fromWhom != ''){
                        newRecord.From_Whom__c = rec.fromWhom;
                    }
                    if(existingRecords.containsKey(rec.recId)){
                        newRecord.id = rec.recId;
                        recordsToUpsert.add(newRecord);
                    }else{
                        recordsToUpsert.add(newRecord);
                    }
                }
            }
            idsToDelete = existingRecords.keySet();
            if(!recordsToUpsert.isEmpty()){
                for(blue_Sheet__C rec : recordsToUpsert){
                    if(existingRecords.containsKey(rec.Id)){
                        idsToDelete.remove(rec.Id);
                    }
                }
            }
            if (!recordsToUpsert.isEmpty()) {
                upsert recordsToUpsert;
            }
            if (!idsToDelete.isEmpty()) {
                delete [SELECT Id FROM Blue_Sheet__c WHERE Id IN :idsToDelete];
            }
            
        }catch(Exception e){
            ExceptionHandler.logException('blueSheetController', 'saveblueSheetData', e);
        }
    }
    
    
    
    
    @AuraEnabled(cacheable=true)
    public static List<BlueSheetData> getBlueSheetData(String opportunityId) {
        List<BlueSheetData> blueSheetDataList = new List<BlueSheetData>();
        try{
            List<Blue_Sheet__c> blueSheets = [
                SELECT Id, OpportunityId__c, Role__c,Buying_Influences_Involved__c,Buying_Influence_Name__c, Degree_Of_Influence__c, Mode__c, Buying_Influence_Key_Win_Results__c, 
                Evidence_to_support_your_Rating__c, Rating_5_to_5__c, Ideal_Customer_Criteria__c, Match_to_Criteria_5_to_5__c,Type__c,Summary_Of_My_Position_Today__c,flag__c,
                Possible_Actions__c, What__c, Who__c, When__c,Information_Needed__c,From_Whom__c, who_Name__c, Whom_Name__c
                FROM Blue_Sheet__c
                WHERE OpportunityId__c = :opportunityId
            ];
            
            
            for (Blue_Sheet__c bs : blueSheets) {
                BlueSheetData data = new BlueSheetData();
                data.Ids = bs.Id;
                data.buyingInfluences = bs.Buying_Influences_Involved__c;
                if(bs.Buying_Influences_Involved__c != null){
                    data.buyingInfluences  = bs.Buying_Influences_Involved__c;
                    data.buyingInfluenceName = bs.Buying_Influence_Name__c;
                    data.selectedValue = true;  
                }
                data.role = bs.Role__c;
                data.degreeOfInfluence = bs.Degree_Of_Influence__c;
                data.mode = bs.Mode__c;
                data.winResult = bs.Buying_Influence_Key_Win_Results__c;
                data.evidence = bs.Evidence_to_support_your_Rating__c;
                data.rating = bs.Rating_5_to_5__c;
                data.idealCustomerCriteria = bs.Ideal_Customer_Criteria__c;
                data.matchCriteria = bs.Match_to_Criteria_5_to_5__c;
                data.type = bs.Type__c;
                data.summryOfMyPosition  = bs.Summary_Of_My_Position_Today__c;
                data.possibleActions  = bs.Possible_Actions__c;
                data.what  = bs.What__c;
                data.flag = bs.flag__c;
                if(bs.Who__c != null){
                    data.who  = bs.Who__c;
                    data.notifyName = bs.who_Name__c;
                    data.selectedValue = true;  
                }
                data.whenDate  = String.valueOf(bs.When__c);
                data.informationNeeded  = bs.Information_Needed__c;
                if(bs.From_Whom__c != null){
                    data.fromWhom  = bs.From_Whom__c;
                    data.notifyName = bs.Whom_Name__c;
                    data.selectedValue = true;  
                }
                blueSheetDataList.add(data);
            }
            
        }catch(Exception e){
            ExceptionHandler.logException('blueSheetController', 'getBlueSheetData', e);
        }
        
        return blueSheetDataList;
    }    
    
    public class BlueSheetData {
        @AuraEnabled public String Ids;
        @AuraEnabled public String buyingInfluences;
        @AuraEnabled public String buyingInfluenceName;
        @AuraEnabled public String role;
        @AuraEnabled public String degreeOfInfluence;
        @AuraEnabled public String mode;
        @AuraEnabled public String winResult;
        @AuraEnabled public String evidence;
        @AuraEnabled public String rating;
        @AuraEnabled public String idealCustomerCriteria;
        @AuraEnabled public String matchCriteria;
        @AuraEnabled public String type;
        @AuraEnabled public String summryOfMyPosition;
        @AuraEnabled public String possibleActions;
        @AuraEnabled public String what;
        @AuraEnabled public String who;
        @AuraEnabled public String whenDate;
        @AuraEnabled public String informationNeeded;
        @AuraEnabled public String fromWhom;
        @AuraEnabled public Boolean selectedValue;
        @AuraEnabled public String notifyName;
        @AuraEnabled public String flag;
        
        
    }
    public class BuyingInfluence {
        public String id;
        public String recId;
        public String type;
        public String buyingInfluences;
        public String role;
        public String degreeOfInfluence;
        public String mode;
        public String winResult;
        public String evidence;
        public String rating;
        public String flag;

    }
    
    
    public class IdealCustomer {
        public String id;
        public String recId;
        public String type;
        public String idealCustomerCriteria;
        public String matchCriteria;
        public String flag;
    }
    public class Strength {
        public String id;
        public String recId;
        public String type;
        public String summryOfMyPosition;
        public String possibleActions;
        public String what;
        public String who;
        public String whenDate;
    }
    public class RedFlag {
        public String id;
        public String recId;
        public String type;
        public String summryOfMyPosition;
        public String possibleActions;
        public String informationNeeded;
        public String fromWhom;
    }
}