force-app/main/default/objects/Opportunity/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget availability and Budget Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, Own Source</fullName>
            </value>
            <value>
                <fullName>Yes, Loan Approved</fullName>
            </value>
            <value>
                <fullName>Loan In Progress</fullName>
            </value>
            <value>
                <fullName>Budget not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CurrentValidationTime__c.field-meta.xml
<CustomField>
    <fullName>CurrentValidationTime__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>CurrentValidationTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Entry_side__c.field-meta.xml
<CustomField>
    <fullName>Entry_side__c</fullName>
    <label>Entry Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Heating_Type__c.field-meta.xml
<CustomField>
    <fullName>Heating_Type__c</fullName>
    <label>Heating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Dual (Electric &amp; Steam)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Infrastructure_completed_in_30_days__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_completed_in_30_days__c</fullName>
    <label>Infrastructure completed in 30 days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_timeline__c</fullName>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-30 days</fullName>
            </value>
            <value>
                <fullName>31-60 days</fullName>
            </value>
            <value>
                <fullName>61-90 days</fullName>
            </value>
            <value>
                <fullName>greater than 90 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reasons_for_Closed_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reasons_for_Closed_Lost__c</fullName>
    <label>Reasons for Closed Lost</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competition (Name to be specified)</fullName>
            </value>
            <value>
                <fullName>Product Availability</fullName>
            </value>
            <value>
                <fullName>Not possible to install</fullName>
            </value>
            <value>
                <fullName>Past Experience</fullName>
            </value>
            <value>
                <fullName>Decision Makers choice</fullName>
            </value>
            <value>
                <fullName>Preference for imported product</fullName>
            </value>
            <value>
                <fullName>Budget restriction</fullName>
            </value>
            <value>
                <fullName>Warranty Terms</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>AMC Terms not agreed</fullName>
            </value>
            <value>
                <fullName>Invalid Product Requirement</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recapture_Processed__c.field-meta.xml
<CustomField>
    <fullName>Recapture_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recapture Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Space_availability__c.field-meta.xml
<CustomField>
    <fullName>Space_availability__c</fullName>
    <label>Space Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityRecaptureBatch.cls
public class OpportunityRecaptureBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date targetDate = System.today().addDays(-60);
        Date startDate = targetDate;
        Date endDate = targetDate.addDays(1);
        String closedLostStage = 'Closed Lost';
        String query = 'SELECT Id, AccountId, Name, Description, StageName, Amount, Probability,Space_availability__c, '+
            'Budget__c,Heating_Type__c,Entry_side__c,Reasons_for_Closed_Lost__c,Purchase_timeline__c,Site__c,OwnerId,Infrastructure_completed_in_30_days__c '+
            'FROM Opportunity ' +
            'WHERE StageName = :closedLostStage ' +
            'AND Closed_Lost_Date__c >= :startDate ' +
            'AND Closed_Lost_Date__c < :endDate ' +
            'AND Recapture_Processed__c = FALSE';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity> listOfOpportunities) {
        List<Opportunity> opportunitiesToInsert = new List<Opportunity>();
        List<Task> tasksToInsert = new List<Task>();
        List<OpportunityLineItem> lineItemsToInsert = new List<OpportunityLineItem>();
        Map<Id, List<OpportunityLineItem>> opportunityLineItemsMap = new Map<Id, List<OpportunityLineItem>>();
        Set<Id> opportunityIds = new Set<Id>();
        for (Opportunity opp : listOfOpportunities) {
            if (hasValidReason(opp.Reasons_for_Closed_Lost__c)) {
                opportunityIds.add(opp.Id);
            }
        }
        if (!opportunityIds.isEmpty()) {
            try {
                List<OpportunityLineItem> listOfOppLineItems = [
                    SELECT OpportunityId, PricebookEntryId, Quantity, UnitPrice, Discount 
                    FROM OpportunityLineItem 
                    WHERE OpportunityId IN :opportunityIds];
                if(!listOfOppLineItems.isEmpty()){
                    for (OpportunityLineItem oli : listOfOppLineItems) {
                        if (!opportunityLineItemsMap.containsKey(oli.OpportunityId)) {
                            opportunityLineItemsMap.put(oli.OpportunityId, new List<OpportunityLineItem>());
                        }
                        opportunityLineItemsMap.get(oli.OpportunityId).add(oli);
                    }
                }
                for (Opportunity opp : listOfOpportunities) {
                    if (opportunityLineItemsMap.containsKey(opp.Id)) {
                        Opportunity newRecaptureOpp = opp.clone(false, true, false, false);
                        newRecaptureOpp.Name = 'Recapture - ' + opp.Name;
                        newRecaptureOpp.CloseDate = System.today().addDays(30);
                        newRecaptureOpp.AccountId = opp.AccountId;
                        newRecaptureOpp.OwnerId = opp.OwnerId;
                        newRecaptureOpp.StageName = ConstantUtilities.OPP_STAGE_QUALIFICATION;
                        newRecaptureOpp.CurrentValidationTime__c = System.now();
                        opportunitiesToInsert.add(newRecaptureOpp);
                        
                        Task recaptureTask = new Task();
                        recaptureTask.Subject = ConstantUtilities.RECAPTURE_SUBJECT;
                        recaptureTask.OwnerId = opp.OwnerId;
                        recaptureTask.Status = ConstantUtilities.RECAPTURE_STATUS;
                        recaptureTask.Priority = ConstantUtilities.RECAPTURE_PRIORITY;
                        recaptureTask.ActivityDate = System.today().addDays(7);  
                        tasksToInsert.add(recaptureTask);
                        opp.Recapture_Processed__c = true;
                    }
                }
                if (!opportunitiesToInsert.isEmpty()) {
                    insert opportunitiesToInsert;
                    for (Integer i = 0; i < opportunitiesToInsert.size(); i++) {
                        tasksToInsert[i].WhatId = opportunitiesToInsert[i].Id;
                    }
                    insert tasksToInsert;
                    
                    for (Opportunity opp : listOfOpportunities) {
                        if (opportunityLineItemsMap.containsKey(opp.Id)) {
                            for (OpportunityLineItem oldLineItem : opportunityLineItemsMap.get(opp.Id)) {
                                OpportunityLineItem newLineItem = oldLineItem.clone(false, true, false, false);
                                newLineItem.OpportunityId = opportunitiesToInsert[listOfOpportunities.indexOf(opp)].Id;
                                lineItemsToInsert.add(newLineItem);
                            }
                        }
                    }
                    
                    if (!lineItemsToInsert.isEmpty()) {
                        insert lineItemsToInsert;
                    }
                }
                
                if (!listOfOpportunities.isEmpty()) {
                    update listOfOpportunities;
                }
                
            } catch (Exception e) {
                ExceptionHandler.logException('OpportunityRecaptureBatch', 'execute', e);
            }
        }
    }
    
    public void finish(Database.BatchableContext bc) {
    }
    
    private Boolean hasValidReason(String reasonsForClosedLost) {
        if (String.isNotBlank(reasonsForClosedLost)) {
            Set<String> reasonsSet = new Set<String>(reasonsForClosedLost.split(';'));
            for (String reason : reasonsSet) {
                if (ConstantUtilities.RECAPTURE_OPP_CLOSEDLOST_REASONS.contains(reason)) {
                    return true;
                }
            }
        }
        return false;
    }
}