force-app/main/default/objects/Opportunity/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILM</fullName>
                <label>Industrial Laundry Machine</label>
            </value>
            <value>
                <fullName>IDW</fullName>
                <label>Industrial Dishwasher</label>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reasons_for_Closed_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reasons_for_Closed_Lost__c</fullName>
    <label>Reasons for Closed Lost</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competition (Name to be specified)</fullName>
            </value>
            <value>
                <fullName>Product Availability</fullName>
            </value>
            <value>
                <fullName>Not possible to install</fullName>
            </value>
            <value>
                <fullName>Past Experience</fullName>
            </value>
            <value>
                <fullName>Decision Makers choice</fullName>
            </value>
            <value>
                <fullName>Preference for imported product</fullName>
            </value>
            <value>
                <fullName>Budget restriction</fullName>
            </value>
            <value>
                <fullName>Warranty Terms</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>AMC Terms not agreed</fullName>
            </value>
            <value>
                <fullName>Invalid Product Requirement</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Quote_Approval__c.field-meta.xml
<CustomField>
    <fullName>Customer_Quote_Approval__c</fullName>
    <label>Customer Quote Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Change Request/Revision.</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <isActive>false</isActive>
                <label>Invalid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/ExpiredQuotes__c.field-meta.xml
<CustomField>
    <fullName>ExpiredQuotes__c</fullName>
    <formula>IF(
    SBQQ__ExpirationDate__c&lt; TODAY(),
    true,
    false
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ExpiredQuotes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <formula>IF(ISPICKVAL(SBQQ__Opportunity2__r.Product_category__c, &apos;ILM&apos;),&apos;Industrial Laundry Machine&apos;, IF(ISPICKVAL(SBQQ__Opportunity2__r.Product_category__c, &apos;IDW&apos;), &apos;Industrial Dishwasher&apos;,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
public class OpportunityTriggerHelper {
    public static void handleBeforeInsert(List<Opportunity> newOpportunities) {
        Set<Id> accountIds = new Set<Id>();
        for (Opportunity opp : newOpportunities) {
            if (opp.AccountId != null) {
                accountIds.add(opp.AccountId);
            }
        }
        
        Map<Id, Account> accountsMap = new Map<Id, Account>(
            [SELECT Id, CurrencyIsoCode FROM Account WHERE Id IN :accountIds]
        );
        
        for (Opportunity opp : newOpportunities) {
            if (opp.AccountId != null && accountsMap.containsKey(opp.AccountId) && accountsMap.get(opp.AccountId).CurrencyIsoCode != null) {
                opp.CurrencyIsoCode = accountsMap.get(opp.AccountId).CurrencyIsoCode;
            }
        }
        Set<String> productCategoryAPINames = new Set<String>();
        for (Opportunity opp : newOpportunities) {
            if (opp.Product_Category__c != null) {
                productCategoryAPINames.add(opp.Product_Category__c);
            }
        }
        Map<String, Id> apiNameToPricebookIdMap = new Map<String, Id>();
        Map<String, String> apiNameToLabelMap = ConstantUtilities.CATEGORY_TO_PRICEBOOK_NAME_MAP;
        Map<String, String> labelToApiNameMap = new Map<String, String>();
        for (String apiName : apiNameToLabelMap.keySet()) {
            labelToApiNameMap.put(apiNameToLabelMap.get(apiName), apiName);
        }
        if (!labelToApiNameMap.isEmpty()) {
            List<Pricebook2> pricebooks = [
                SELECT Id, Name
                FROM Pricebook2
                WHERE Name IN :labelToApiNameMap.keySet()
            ];
            for (Pricebook2 pb : pricebooks) {
                if (labelToApiNameMap.containsKey(pb.Name)) {
                    String apiName = labelToApiNameMap.get(pb.Name);
                    apiNameToPricebookIdMap.put(apiName, pb.Id);
                }
            }
        }
        for (Opportunity opp : newOpportunities) {
            if (opp.Product_Category__c != null && apiNameToPricebookIdMap.containsKey(opp.Product_Category__c)) {
                Id pricebookId = apiNameToPricebookIdMap.get(opp.Product_Category__c);
                opp.Pricebook2Id = pricebookId;
                opp.SBQQ__QuotePricebookId__c = pricebookId;
            }
        }
    }
    public static void handleBeforeUpdate(List<Opportunity> newOpportunityList, Map<Id, Opportunity> oldOpportunityMap) {
        try {
            Set<Id> opportunityIds = new Set<Id>();
            Map<Id, SBQQ__Quote__c> validQuoteMap = new Map<Id, SBQQ__Quote__c>();
            for (Opportunity opp : newOpportunityList) {
                if (opp.StageName == ConstantUtilities.OPPORTUNITY_CLOSEWON && oldOpportunityMap.get(opp.Id).StageName != ConstantUtilities.OPPORTUNITY_CLOSEWON) {
                    opportunityIds.add(opp.Id);
                }
            }
            if (opportunityIds.isEmpty()) {
                return;
            }
            for (SBQQ__Quote__c quote : [SELECT Id, SBQQ__Opportunity2__c, SBQQ__Primary__c, SBQQ__Status__c, ExpiredQuotes__c, Customer_Quote_Approval__c
                                         FROM SBQQ__Quote__c
                                         WHERE SBQQ__Opportunity2__c IN :opportunityIds 
                                         and ExpiredQuotes__c = FALSE and SBQQ__Primary__c = TRUE and SBQQ__Status__c = :ConstantUtilities.QUOTE_APPROVED 
                                         and Customer_Quote_Approval__c = :ConstantUtilities.QUOTE_CUSTOMER_ACCEPTED
                                        ]){
                                            validQuoteMap.put(quote.SBQQ__Opportunity2__c, quote);
                                        }
            for (Opportunity opp : newOpportunityList) {
                if (opp.StageName == ConstantUtilities.OPPORTUNITY_CLOSEWON && !validQuoteMap.containsKey(opp.Id)) {
                    opp.addError(ConstantUtilities.OPPORTUNITY_CLOSEWON_ERROR);
                }
            }
            
            for (Opportunity opp : newOpportunityList){
                Opportunity oldOpp = oldOpportunityMap.get(opp.Id);
                if (opp.StageName == ConstantUtilities.OPP_STAGE_CLOSED_LOST && 
                    oldOpp.StageName != ConstantUtilities.OPP_STAGE_CLOSED_LOST) {
                        Set<String> reasonsSet = new Set<String>(opp.Reasons_for_Closed_Lost__c.split(';'));
                        if (hasValidReason(reasonsSet, ConstantUtilities.RECAPTURE_OPP_CLOSEDLOST_REASONS)) {
                            opp.Closed_Lost_Date__c = System.today();  
                        }
                    }
            }
            
        } catch (Exception e) {
            ExceptionHandler.logException('OpportunityTriggerHelper' , 'handleBeforeUpdate', e);
        }
    }
    
    public static Boolean hasValidReason(Set<String> reasonsSet, Set<String> validReasons) {
        for (String reason : validReasons) {
            if (reasonsSet.contains(reason)) {
                return true;
            }
        }
        return false;
    }
    
    
}