force-app/main/default/objects/Freight_Price_Mapping__mdt/Freight_Price_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Freight Price Mapping</label>
    <pluralLabel>Freight Price Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Freight_Price_Mapping__mdt/fields/Tata_Ace__c.field-meta.xml
<CustomField>
    <fullName>Tata_Ace__c</fullName>
    <label>Tata Ace</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Price_Mapping__mdt/fields/X14__c.field-meta.xml
<CustomField>
    <fullName>X14__c</fullName>
    <label>14</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Price_Mapping__mdt/fields/X17__c.field-meta.xml
<CustomField>
    <fullName>X17__c</fullName>
    <label>17</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Price_Mapping__mdt/fields/X19__c.field-meta.xml
<CustomField>
    <fullName>X19__c</fullName>
    <label>19</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Price_Mapping__mdt/fields/X22__c.field-meta.xml
<CustomField>
    <fullName>X22__c</fullName>
    <label>22</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Capacity_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Utilization__c</fullName>
    <label>Capacity Utilization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Calculated_On_City__c.field-meta.xml
<CustomField>
    <fullName>Freight_Calculated_On_City__c</fullName>
    <label>Freight Calculated On City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Freight_Calculated_On_State__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Kokrajhar</fullName>
            </value>
            <value>
                <fullName>Brepta</fullName>
            </value>
            <value>
                <fullName>Guwathi</fullName>
            </value>
            <value>
                <fullName>Dispur</fullName>
            </value>
            <value>
                <fullName>Tezpur</fullName>
            </value>
            <value>
                <fullName>Nagaon</fullName>
            </value>
            <value>
                <fullName>Jorgat</fullName>
            </value>
            <value>
                <fullName>Sivsagar</fullName>
            </value>
            <value>
                <fullName>Dibrughar</fullName>
            </value>
            <value>
                <fullName>Tinsukiya</fullName>
            </value>
            <value>
                <fullName>Golaghat</fullName>
            </value>
            <value>
                <fullName>Dimpaur</fullName>
            </value>
            <value>
                <fullName>Silchar</fullName>
            </value>
            <value>
                <fullName>Tirpura</fullName>
            </value>
            <value>
                <fullName>Agartala</fullName>
            </value>
            <value>
                <fullName>Udaiput</fullName>
            </value>
            <value>
                <fullName>Aizwal</fullName>
            </value>
            <value>
                <fullName>Implhal</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Gangtok</fullName>
            </value>
            <value>
                <fullName>Vizag</fullName>
            </value>
            <value>
                <fullName>Vijayawada</fullName>
            </value>
            <value>
                <fullName>Rajamandri</fullName>
            </value>
            <value>
                <fullName>Guntur</fullName>
            </value>
            <value>
                <fullName>Kakinada</fullName>
            </value>
            <value>
                <fullName>Ongole</fullName>
            </value>
            <value>
                <fullName>Vijayanagaram</fullName>
            </value>
            <value>
                <fullName>Srikakulam</fullName>
            </value>
            <value>
                <fullName>Betthia</fullName>
            </value>
            <value>
                <fullName>Gopalganj</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Calculated_On_State__c.field-meta.xml
<CustomField>
    <fullName>Freight_Calculated_On_State__c</fullName>
    <label>Freight Calculated On State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu And Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Kargil</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Leh</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Nepal</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Silvassa</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Fright_Charges__c.field-meta.xml
<CustomField>
    <fullName>Fright_Charges__c</fullName>
    <label>Freight Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Total_Area_Feet__c.field-meta.xml
<CustomField>
    <fullName>Total_Area_Feet__c</fullName>
    <description>Freight Total area feild</description>
    <label>Total Area Feet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Vehicle_1__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_1__c</fullName>
    <label>Vehicle 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Ace</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Vehicle_2__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_2__c</fullName>
    <label>Vehicle 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Ace</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Vehicle_3__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_3__c</fullName>
    <label>Vehicle 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Ace</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Vehicle_4__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_4__c</fullName>
    <label>Vehicle 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tata Ace</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FreightCalculatorController.cls
/*
@Author : Aman Sagar
@CreatedDate : 28th Aug 2024
@Description : This class is calculating Freight charges.
*/
public class FreightCalculatorController {
    @AuraEnabled
    public static List<ProductLineWrapper> getProductsfromQuoteLine(String recordId){
        List<ProductLineWrapper> productLineWrapperList = new List<ProductLineWrapper>();
        try{
            for(SBQQ__QuoteLine__c quoteline : [select Id,SBQQ__Product__r.Name, SBQQ__Product__r.cgcloud__Size__c,
                                                 SBQQ__Quantity__c,SBQQ__Product__r.ProductCode,SBQQ__Quote__c 
                                                 from SBQQ__QuoteLine__c
                                                 where SBQQ__Quote__c =: recordId
                                                ]){
                                                  ProductLineWrapper productLineWrapper = new ProductLineWrapper();  
                                                    productLineWrapper.quantity = quoteline.SBQQ__Quantity__c;
                                                    productLineWrapper.Model = quoteline.SBQQ__Product__r.ProductCode;
                                                    productLineWrapper.productName = quoteline.SBQQ__Product__r.Name;
                                                    productLineWrapper.areaFeet = quoteline.SBQQ__Product__r.cgcloud__Size__c;
                                                    productLineWrapperList.add(productLineWrapper);
                                                }
            
            return productLineWrapperList;
        }
        catch(Exception e){
            ExceptionHandler.logException('FreightCalculatorController' , 'getProductsfromQuoteLine', e);
        }
        
        return null;
    }
    
    @AuraEnabled
    public static Freight_Price_Mapping__mdt getFreightPrice(String state, String city){
        try{
            Freight_Price_Mapping__mdt price = [select Id,State__c,City__c,Tata_Ace__c,X22__c,X19__c,X17__c,X14__c 
                                                from Freight_Price_Mapping__mdt 
                                                where State__C =: state and City__c =: city
                                               ]; 
            return price;
        }
        catch(Exception e){
            ExceptionHandler.logException('FreightCalculatorController' , 'getFreightPrice', e);
        }
        
        return null;
    }
    @AuraEnabled
    public static void updatingQuote(String quoteId,String vehicle1, String vehicle2, String vehicle3, String vehicle4, Decimal capacity, Decimal freightPrice, Decimal TotalArea, String freightCity,String freightState) {
        try {
            SBQQ__Quote__c quote = new SBQQ__Quote__c();
            quote.id = quoteId;
                quote.Vehicle_1__c = vehicle1;
                quote.Vehicle_2__c = vehicle2;
                quote.Vehicle_3__c = vehicle3;
                quote.Vehicle_4__c = vehicle4;
                quote.Capacity_Utilization__c = capacity;
                quote.Fright_Charges__c = freightPrice;
                quote.Total_Area_Feet__c = TotalArea;
                quote.Freight_Calculated_On_State__c = freightState;
				quote.Freight_Calculated_On_City__c = freightCity;
            update quote;
            
        } catch (Exception e) {
            ExceptionHandler.logException('FreightCalculatorController' , 'updatingQuote', e);
        }
    }
    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getVehicleCapacities() {
        Map<String, Integer> vehicleCapacities = new Map<String, Integer>{
            ConstantUtilities.TATA => ConstantUtilities.TATA_ACE,
                ConstantUtilities.FOUR => ConstantUtilities.VEHICLE14,
                ConstantUtilities.SEVEN => ConstantUtilities.VEHICLE17,
                ConstantUtilities.NINE => ConstantUtilities.VEHICLE19,
                ConstantUtilities.TWO => ConstantUtilities.VEHICLE22,
                ConstantUtilities.NONE => ConstantUtilities.VEHICLE_NONE
                };
                    return vehicleCapacities;
    }
      @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getPicklistValues(String stateValue) {
        Map<String, List<String>> picklistValues = new Map<String, List<String>>();
        
        // Retrieve state picklist values
        Schema.DescribeFieldResult stateFieldDescribe = SBQQ__Quote__c.Freight_Calculated_On_State__c.getDescribe();
        List<Schema.PicklistEntry> statePicklistEntries = stateFieldDescribe.getPicklistValues();
        List<String> stateValues = new List<String>();
        for (Schema.PicklistEntry entry : statePicklistEntries) {
            stateValues.add(entry.getLabel());
        }
        picklistValues.put('stateValues', stateValues);
        
        // Retrieve city picklist values
        List<String> cityValues = new List<String>();
        if (stateValue != null) {
            Schema.DescribeFieldResult cityFieldDescribe = SBQQ__Quote__c.Freight_Calculated_On_City__c.getDescribe();
            List<Schema.PicklistEntry> cityPicklistEntries = cityFieldDescribe.getPicklistValues();
            
            // Get field dependencies
            Schema.PicklistEntry[] statePicklistEntriesArray = stateFieldDescribe.getPicklistValues();
            Map<String, List<String>> dependentValues = new Map<String, List<String>>();
            for (Schema.PicklistEntry stateEntry : statePicklistEntriesArray) {
                dependentValues.put(stateEntry.getValue(), new List<String>());
            }
            
            // Fetch dependent picklist values
            for (Schema.PicklistEntry cityEntry : cityPicklistEntries) {
                Schema.DescribeFieldResult cityFieldResult = SBQQ__Quote__c.Freight_Calculated_On_City__c.getDescribe();
                Map<String, Schema.PicklistEntry> picklistEntryMap = new Map<String, Schema.PicklistEntry>();
                for (Schema.PicklistEntry entry : cityFieldResult.getPicklistValues()) {
                    picklistEntryMap.put(entry.getValue(), entry);
                }
                
                // Check if the city value is valid for the selected state
                if (picklistEntryMap.containsKey(stateValue)) {
                    dependentValues.get(stateValue).add(cityEntry.getLabel());
                    
                }
                system.debug('**dependentValues'+dependentValues);
            }
            cityValues = dependentValues.containsKey(stateValue) ? dependentValues.get(stateValue): new List<String>();
        }
        system.debug('cityValues'+cityValues);
        picklistValues.put('cityValues', cityValues);
        return picklistValues;
    }
    class ProductLineWrapper{
        @AuraEnabled
        public String productName {get;set;}
        @AuraEnabled
        public String Model {get;set;}
        @AuraEnabled
        public String areaFeet {get;set;}
        @AuraEnabled
        public decimal quantity {get;set;}
        
    }    
}