force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <label>API Configuration</label>
    <nameField>
        <displayFormat>ACN-{000000000}</displayFormat>
        <label>API Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense Sync Request</fullName>
            </value>
            <value>
                <fullName>LeaveUpdate</fullName>
            </value>
            <value>
                <fullName>Attendance Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Cancelled Sync</fullName>
            </value>
            <value>
                <fullName>Account Request</fullName>
                <isActive>false</isActive>
                <label>Account Request</label>
            </value>
            <value>
                <fullName>Meeting Request</fullName>
                <isActive>false</isActive>
                <label>Meeting Request</label>
            </value>
            <value>
                <fullName>Order Sync Request</fullName>
                <isActive>false</isActive>
                <label>Order Sync Request</label>
            </value>
            <value>
                <fullName>Product Query</fullName>
                <isActive>false</isActive>
                <label>Product Query</label>
            </value>
            <value>
                <fullName>Product Sync Request</fullName>
                <isActive>false</isActive>
                <label>Product Sync Request</label>
            </value>
            <value>
                <fullName>Sample Request</fullName>
                <isActive>false</isActive>
                <label>Sample Request</label>
            </value>
            <value>
                <fullName>Site Sync Request</fullName>
                <isActive>false</isActive>
                <label>Site Sync Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/JSON_Key__c.field-meta.xml
<CustomField>
    <fullName>JSON_Key__c</fullName>
    <label>JSON Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Expense_Line_Item__c</fullName>
            </value>
            <value>
                <fullName>Attendance__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Order_Installment__c</fullName>
            </value>
            <value>
                <fullName>OrderItem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/Integration_Handler__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type will be used to store the credential and other details  of third party system.</description>
    <label>Integration Handler</label>
    <pluralLabel>Integration Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Handler__mdt/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/is_Static_Token__c.field-meta.xml
<CustomField>
    <fullName>is_Static_Token__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>if the Static Bearer token is Provided to you then Marke this as True and add the static token value</inlineHelpText>
    <label>is Static Token</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Static_Token_Value__c.field-meta.xml
<CustomField>
    <fullName>Static_Token_Value__c</fullName>
    <inlineHelpText>Bearer Token which will get user for authentication</inlineHelpText>
    <label>Static Token Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Generation_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_Generation_URL__c</fullName>
    <label>Token Generation URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Token_Http_Method__c</fullName>
    <label>Token Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Token_Request_Body__c</fullName>
    <label>Token Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Advance_Amount_p__c.field-meta.xml
<CustomField>
    <fullName>Advance_Amount_p__c</fullName>
    <formula>(Advance_Received_Amount__c/ Total_Amount_Including_GST__c)</formula>
    <label>Advance Amount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Advance_Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advance_Received_Amount__c</fullName>
    <label>Advance Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>IF(Total_Amount_Including_GST__c - Total_Amount_Received__c &lt; 0, 
   0, 
   Total_Amount_Including_GST__c - Total_Amount_Received__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pending_Amount_p__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount_p__c</fullName>
    <formula>(Pending_Amount__c / Total_Amount_Including_GST__c)</formula>
    <label>Pending Amount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Synced_with_the_IFB_Internal_Portal__c.field-meta.xml
<CustomField>
    <fullName>Synced_with_the_IFB_Internal_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced with the IFB Internal Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/Order_Installment__c.object-meta.xml
<CustomObject>
    <label>Order Installment</label>
    <nameField>
        <displayFormat>OIN-{0000000}</displayFormat>
        <label>Order Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Installments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Installment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Installments</relationshipLabel>
    <relationshipName>Order_Installments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/fields/Parent_ID_Config__c.field-meta.xml
<CustomField>
    <fullName>Parent_ID_Config__c</fullName>
    <formula>CASESAFEID(Order__c)</formula>
    <label>Parent ID Config</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/fields/Synced_with_the_IFB_Internal_Portal__c.field-meta.xml
<CustomField>
    <fullName>Synced_with_the_IFB_Internal_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced with the IFB Internal Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/fields/Transaction_Proof_Link__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Proof_Link__c</fullName>
    <label>Transaction Proof Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Installment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationHandler.cls
public without sharing class IntegrationHandler {
    
    //Added by Atul : June 6,2024 : this method will be used to send the objects data to out of salesfroce to IFB internal systems.
    @future(callout=true)
    public static void sendObejectDataToIFBInternalSys(List<Id> idListToProccess, String actionType){
        try{
            system.debug('idListToProccess'+idListToProccess);
            Map<String, String> fieldAPIVsConfigRecMap = new Map<String, String>();
            Map<String, Map<String, String>> childfieldAPIVsConfigRecMap = new Map<String, Map<String, String>>(); 
            Map<String, String> childRealtionshipMap = new Map<String, String>();
            Boolean isFilesIncluded = false;
            String fileJsonLabel;
            List<Sobject> childSobjectList = new List<Sobject>();
            Map<String,Map<String, Object>> mapOfParentObjectDataWithId = new Map<String,Map<String, Object>>();
            Map<String, Map<String, List<Map<String, Object>>>> parentIdVsChildDataList = new Map<String, Map<String, List<Map<String, Object>>>>();
            Map<Id, Map<String, Object>> parentRecordVsFileMap = new Map<Id, Map<String, Object>>();
            //This API_Configuration__c obecjt records are having the field API Name and there json tag value 
            Integration_Handler__mdt integrationHandlerInstance = Integration_Handler__mdt.getInstance(actionType.replace(' ','_'));
            if(integrationHandlerInstance != null && integrationHandlerInstance.Is_Active__c){
                
                for(API_Configuration__c apiConfigInst : [select API_Type__c,Data_Type__c,Field_API_Name__c,JSON_Key__c,Object_Name__c,
                                                          Include_Files__c, Parent_Object_Name__c
                                                          from API_Configuration__c 
                                                          where (Object_Name__c =:String.valueOf(idListToProccess[0].getsobjecttype()) 
                                                                 OR Parent_Object_Name__c =:String.valueOf(idListToProccess[0].getsobjecttype()))
                                                          AND API_Type__c= :actionType])
                {    
                    if(apiConfigInst.Include_Files__c){
                        isFilesIncluded = true; // try to have this thing on custom metadata type records so this additional condition can be eleiminted.  or we can have the another query just to query this specific value.
                        fileJsonLabel = apiConfigInst.JSON_Key__c;
                    }else{
                        //storing parent fields and child fields in respective map to build query.
                        if(apiConfigInst.Parent_Object_Name__c == null){
                            fieldAPIVsConfigRecMap.put(apiConfigInst.Field_API_Name__c, apiConfigInst.JSON_Key__c);
                        }
                        else if(apiConfigInst.Parent_Object_Name__c != null){
                            if(!childfieldAPIVsConfigRecMap.containsKey(apiConfigInst.Object_Name__c)){
                                childfieldAPIVsConfigRecMap.put(apiConfigInst.Object_Name__c, new Map<String, String>{apiConfigInst.Field_API_Name__c => apiConfigInst.JSON_Key__c});
                            }
                            childfieldAPIVsConfigRecMap.get(apiConfigInst.Object_Name__c).put(apiConfigInst.Field_API_Name__c, apiConfigInst.JSON_Key__c);
                        }
                    }
                    
                }
                
                //getting child relationship name to do the query with parent.
                if(!childfieldAPIVsConfigRecMap.isEmpty()){
                    childRealtionshipMap = IntegrationHandler.getChildRelationships(childfieldAPIVsConfigRecMap.keySet(), idListToProccess[0].getsobjecttype());
                }
                
                for(SObject objInst : IntegrationHandler.querySobjectWithSelectedField(idListToProccess, fieldAPIVsConfigRecMap.keySet(),childfieldAPIVsConfigRecMap, childRealtionshipMap,actionType)){
                    Map<String, Object> mapOfobjectData = new Map<String, Object>();
                    
                    //This for loop is storing all the child records in a list to process the json key change out for loop.
                    for(String childObjectAPIName : childfieldAPIVsConfigRecMap.keySet()){
                        if(childRealtionshipMap.containsKey(childObjectAPIName)){
                            if(objInst.getSObjects(childRealtionshipMap.get(childObjectAPIName)) != null){
                                childSobjectList.addAll(objInst.getSObjects(childRealtionshipMap.get(childObjectAPIName)));
                            }
                            
                        }
                    }
                     for (String fieldAPIName : fieldAPIVsConfigRecMap.keySet()) {
                        List<String> fieldParts = fieldAPIName.split('\\.');
                        if (fieldParts.size() == 1) {
                            if (objInst.get(fieldAPIName) != null) {
                                mapOfobjectData.put(fieldAPIVsConfigRecMap.get(fieldAPIName), objInst.get(fieldAPIName));
                            }
                        } else {
                            SObject parentObj = objInst;
                            Boolean isValid = true;
                            for (Integer i = 0; i < fieldParts.size() - 1; i++) {
                                String relationshipName = fieldParts[i];
                                parentObj = parentObj.getSObject(relationshipName);
                                if (parentObj == null) {
                                    isValid = false;
                                    break;
                                }
                            }
                            if (isValid && parentObj.get(fieldParts[fieldParts.size() - 1]) != null) {
                                mapOfobjectData.put(fieldAPIVsConfigRecMap.get(fieldAPIName), parentObj.get(fieldParts[fieldParts.size() - 1]));
                            }
                        }
                    }
                    mapOfParentObjectDataWithId.put(objInst.id,mapOfobjectData );
                    
                }
                for(Sobject sobjInst : childSobjectList){
                    Map<String, Object> mapOfChildobjectData = new Map<String, Object>();
                    
                    for(string fieldAPIName : childfieldAPIVsConfigRecMap.get(sobjInst.getSobjectType().getDescribe().getName()).keySet()){
                        mapOfChildobjectData.put(childfieldAPIVsConfigRecMap.get(sobjInst.getSobjectType().getDescribe().getName()).get(fieldAPIName), sobjInst.get(fieldAPIName));
                    }
                    if(!parentIdVsChildDataList.containsKey((String)sobjInst.get('Parent_ID_Config__c'))){
                        parentIdVsChildDataList.put((String)sobjInst.get('Parent_ID_Config__c'), new Map<String, List<Map<String, Object>>>());
                    }
                    if(!parentIdVsChildDataList.get((String)sobjInst.get('Parent_ID_Config__c')).containsKey((childRealtionshipMap.get(sobjInst.getSobjectType().getDescribe().getName())).replace('__r', ''))){
                        parentIdVsChildDataList.get((String)sobjInst.get('Parent_ID_Config__c')).put((childRealtionshipMap.get(sobjInst.getSobjectType().getDescribe().getName())).replace('__r', ''), new List<Map<String, Object>>{mapOfChildobjectData});
                    }else{
                        parentIdVsChildDataList.get((String)sobjInst.get('Parent_ID_Config__c')).get((childRealtionshipMap.get(sobjInst.getSobjectType().getDescribe().getName())).replace('__r', '')).add(mapOfChildobjectData);
                    }
                }
                //here calling a funcation to get the all related files from parent object.
                if(isFilesIncluded){
                    parentRecordVsFileMap = IntegrationHandler.getFilesForRecords(idListToProccess);
                }
                for(String parentId : mapOfParentObjectDataWithId.keySet()){
                    if(parentRecordVsFileMap.containsKey(parentId) && isFilesIncluded){
                        mapOfParentObjectDataWithId.get(parentId).put(fileJsonLabel,parentRecordVsFileMap.get(parentId).values());
                    }
                    if(parentIdVsChildDataList.containsKey(parentId)){
                        mapOfParentObjectDataWithId.get(parentId).putAll(parentIdVsChildDataList.get(parentId));
                    }
                    
                    
                }
                //Make callout here when we get the details Integration
                String token;
                if( integrationHandlerInstance.is_Static_Token__c ){
                    token = integrationHandlerInstance.Static_Token_Value__c;
                }else{
                    token = IntegrationHandler.generateToken(integrationHandlerInstance);
                }
                IntegrationHandler.makeHttpCallout(integrationHandlerInstance.URL__c, integrationHandlerInstance.Http_Method__c, token, JSON.serialize(mapOfParentObjectDataWithId.values()));
            }else{
                throw new CalloutException('HTTP callout failed: Not able to find any Active Integration handler -custom metadata type for '+actionType +' Record List - '+idListToProccess);
            }
        }catch(Exception e){
            insert Utilities.getExceptionErrorLog('IntegrationHandler' , 'sendObejectDataToIFBInternalSys', e, String.valueOf(idListToProccess));
        }
    }
    
    // Method to make HTTP callouts
    public static HttpResponse makeHttpCallout(String endpoint, String httpMethod, String token, String requestBody) {
        HttpRequest req = new HttpRequest();
        Http http = new Http();
        HttpResponse res;
        System.debug('request Body-->'+ requestBody);
        try {
            req.setEndpoint(endpoint); 
            req.setMethod(httpMethod);
            req.setHeader('Authorization', 'Bearer ' + token);
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Accept', 'application/json');
            req.setTimeout(120000);
            if (requestBody != null && (httpMethod == 'POST' || httpMethod == 'PUT' || httpMethod == 'PATCH')) {
                req.setBody(requestBody);
            }
            res = http.send(req);
            if (res.getStatusCode() == 200) {
                if(httpMethod == 'POST' || httpMethod == 'PUT' || httpMethod == 'PATCH'){
                    insert Utilities.getInfoLog('IntegrationHandler' , 'sendObejectDataToIFBInternalSys', requestBody,'Status Code-'+res.getStatusCode()+' \n Body-'+res.getBody());
                } 
                return res;
            } else {
                insert Utilities.getInfoLog('IntegrationHandler' , 'sendObejectDataToIFBInternalSys', requestBody,'Status Code-'+res.getStatusCode()+' \n Body-'+res.getBody());
                throw new CalloutException('HTTP callout failed with status: ' + res.getStatusCode() + ' and body: ' + res.getBody());
            }
            
        } catch (CalloutException e) {
            throw e;
            
        } catch (Exception e) {
            throw new CalloutException('HTTP callout failed: ' + e.getMessage());
        }
    }
    
    public static List<sObject> querySobjectWithSelectedField(List<Id> ids, Set<String> fieldList, Map<String, Map<String, String>> childFieldRecordMap, Map<String, String>  childRealtionshipMap, String actionType){
        if (ids == null || ids.isEmpty()) {
            throw new IllegalArgumentException('The list of Ids cannot be null or empty.');
        }
        if (fieldList == null || fieldList.isEmpty()) {
            throw new IllegalArgumentException('The list of fields cannot be null or empty.');
        }
        String query = 'Select ' + String.join(fieldList, ',') ;
        if(!childFieldRecordMap.isEmpty()){
            
            for(String childObjectName : childFieldRecordMap.keySet()){
                if(actionType == ConstantUtilities.APIType_ExpenseSyncRequest){
                    query += ',( Select Parent_ID_Config__c,' + String.join(childFieldRecordMap.get(childObjectName).KeySet(), ',') + ' From '+ childRealtionshipMap.get(childObjectName) + ' Where Not_From_Travel_System__c = true ' + ')';
                }else{
                    query += ',( Select Parent_ID_Config__c,' + String.join(childFieldRecordMap.get(childObjectName).KeySet(), ',') + ' From '+ childRealtionshipMap.get(childObjectName) +')';
                }
                  
            }
        } 
        query += ' from ' + ids[0].getsobjecttype() + ' where id in :ids';
        return database.queryWithBinds( query, 
                                       new Map<String, Object>{'ids' => (Object)ids}, 
                                       AccessLevel.SYSTEM_MODE
                                      );
    }
   
    public static Map<String, String> getChildRelationships(Set<String> childObjectNames, Schema.SObjectType parentObjectType) {
        Map<String, String> childRelationshipMap = new Map<String, String>();
        Schema.DescribeSObjectResult parentDescribe = parentObjectType.getDescribe();
        List<Schema.ChildRelationship> childRelationships = parentDescribe.getChildRelationships();
        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
        for (Schema.ChildRelationship childRel : childRelationships) {
            String childSObjectName = childRel.getChildSObject().getDescribe().getName();
            if (childObjectNames.contains(childSObjectName)) {
                childRelationshipMap.put(childSObjectName, childRel.getRelationshipName());
            }
        }
        
        return childRelationshipMap;
    }
	 
    public static Map<Id, Map<String, Object>> getFilesForRecords(List<Id> recordIds) {
        Map<Id, Map<String, Object>> recordFilesMap = new Map<Id, Map<String, Object>>();
        Set<Id> contentDocumentIds = new Set<Id>();
        Map<Id, Id> contentDocumentToRecordMap = new Map<Id, Id>();
        Set<Id> contentVersionIds = new Set<Id>();
        
        List<ContentDocumentLink> contentDocumentLinks = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :recordIds];
        if (contentDocumentLinks.isEmpty()) {
            return recordFilesMap;
        }
        for (ContentDocumentLink cdl : contentDocumentLinks) {
            contentDocumentIds.add(cdl.ContentDocumentId);
            contentDocumentToRecordMap.put(cdl.ContentDocumentId, cdl.LinkedEntityId);
        }
        List<ContentDocument> contentDocuments = [SELECT Id, LatestPublishedVersionId FROM ContentDocument WHERE Id IN :contentDocumentIds];
        
        if (contentDocuments.isEmpty()) {
            return recordFilesMap;
        }
        
        for (ContentDocument cd : contentDocuments) {
            contentVersionIds.add(cd.LatestPublishedVersionId);
        }
        List<ContentVersion> contentVersions = [SELECT Id, ContentDocumentId, Title, FileType, VersionData FROM ContentVersion WHERE Id IN :contentVersionIds];
        
        if (contentVersions.isEmpty()) {
            return recordFilesMap;
        }
        for (ContentVersion cv : contentVersions) {
            Id recordId = contentDocumentToRecordMap.get(cv.ContentDocumentId);
            if (!recordFilesMap.containsKey(recordId)) {
                recordFilesMap.put(recordId, new Map<String, Object>());
            }
            Map<String, Object> fileData = new Map<String, Object>();
            fileData.put('fileName', cv.Title);
            fileData.put('fileType', cv.FileType);
            fileData.put('fileData', EncodingUtil.base64Encode(cv.VersionData));
            recordFilesMap.get(recordId).put(cv.Id, fileData);
        }
        
        return recordFilesMap;
    }
    
    // Custom exception class for callout errors
    public class CalloutException extends Exception {}
    
    public static string generateToken(Integration_Handler__mdt integrationHandlerInstance){
        HttpRequest req = new HttpRequest();
        Http http = new Http();
        HttpResponse res;
        try {
            req.setEndpoint(integrationHandlerInstance.Token_Generation_URL__c); 
            req.setMethod(integrationHandlerInstance.Token_Http_Method__c);
            req.setBody(integrationHandlerInstance.Token_Request_Body__c);
            req.setHeader('Content-Type', 'application/json');
            res = http.send(req);
            if (res.getStatusCode() == 200) {
                Map<string, object> responseDataMap = (Map<string, object>)JSON.deserializeUntyped(res.getBody());
                return String.valueOf(responseDataMap.get('token'));
            } else {
                throw new CalloutException('HTTP Token callout failed with status: ' + res.getStatusCode() + ' and body: ' + res.getBody());
            }
        } catch (Exception e) {
            throw new CalloutException('HTTP Token callout failed: ' + e.getMessage());
        }
    }
    
    @InvocableMethod(label='sendObjectDataToIFB' description='This action will send data dynamically based on action Type')
    public static void sendObejectDataToIFBInternalSysFromFlow(List<flowInput> flowinp){
        List<id> idsToProcess = new List<id>();
        for(flowInput finp : flowinp){
            idsToProcess.addAll(finp.idsListToProccess);
        }
        if(flowinp[0].actionType == 'Purchase Installment Sync'){
            IntegrationHandler.sendOrderInstallmentDataToIFB(idsToProcess, flowinp[0].actionType);
        }else{
            IntegrationHandler.sendObejectDataToIFBInternalSys(idsToProcess, flowinp[0].actionType);
        }
        
    } 
    @future(callout=true)
    public static void sendOrderInstallmentDataToIFB(List<Id> idsToProcess, String actionType){
        Map<Id, Map<String, Object>> fileDataWithRecordIdMap = IntegrationHandler.getFilesForRecords(idsToProcess);
        
        List<OrderInstallmentWrapper> ordInstWrapList = new List<OrderInstallmentWrapper>();
        List<Order_Installment__c> ordInstListForUpdate = new List<Order_Installment__c>();
        try{
            Integration_Handler__mdt integrationHandlerInstance = Integration_Handler__mdt.getInstance(actionType.replace(' ','_'));
            if(integrationHandlerInstance != null && integrationHandlerInstance.Is_Active__c){
                
				List<Order_Installment__c> orderInstallsList = [Select id, Type__c, Transaction_Id__c, Amount__c, Order__c, 
                                                            order__r.TotalAmount, order__r.Advance_Received_Amount__c,
                                                            order__r.Advance_Amount_p__c,order__r.Pending_Amount__c,order__r.Pending_Amount_p__c, Transaction_Proof_Link__c
                                                           From Order_Installment__c where Id in : idsToProcess];
                //Looping on records to Create Wrapper
                for(Order_Installment__c orderInstall : orderInstallsList){
                    OrderInstallmentWrapper OrderInstInst = new OrderInstallmentWrapper();
                    OrderInstallmentWrapper.OrderInstallment ordInstInst = new OrderInstallmentWrapper.OrderInstallment();
                        ordInstInst.Amount = orderInstall.Amount__c;
                        ordInstInst.TransactionId = orderInstall.Transaction_Id__c;
                   		 ordInstInst.TransactionProofLink = orderInstall.Transaction_Proof_Link__c;
                        ordInstInst.sType = orderInstall.Type__c;
                        ordInstInst.Order_InstallmentID = orderInstall.id;
                    	ordInstInst.OrderId = orderInstall.order__c;
                    
                    OrderInstInst.Order_Installments = new List<OrderInstallmentWrapper.OrderInstallment>{ordInstInst};
                    OrderInstInst.PendingAmountPercentage = orderInstall.order__r.Pending_Amount_p__c;
                    OrderInstInst.PendingAmount = orderInstall.order__r.Pending_Amount__c;
                    OrderInstInst.AdvanceAmountPercentage = orderInstall.order__r.Advance_Amount_p__c;
                    OrderInstInst.AdvanceReceivedAmount = orderInstall.order__r.Advance_Received_Amount__c;
                    OrderInstInst.OrderTotalAmount = orderInstall.order__r.TotalAmount;
                    
                    OrderInstInst.sId = orderInstall.order__c;
                    System.debug(fileDataWithRecordIdMap.get(orderInstall.id).values());
                    ordInstWrapList.add(OrderInstInst);
                }
                String requestBody = ((JSON.serialize(ordInstWrapList)).replace('sId','Id')).replace('sType','Type');
                //Make callout here when we get the details Integration
                String token = IntegrationHandler.generateToken(integrationHandlerInstance);
                HttpResponse response = IntegrationHandler.makeHttpCallout(integrationHandlerInstance.URL__c, integrationHandlerInstance.Http_Method__c, token, requestBody);
                if(response.getStatusCode() == 200){
                    for(Order_Installment__c orderInstall : orderInstallsList){
                        Order_Installment__c ordIns = new Order_Installment__c();
                        ordIns.Id = orderInstall.id;
                        ordIns.Synced_with_the_IFB_Internal_Portal__c = true;
                        ordInstListForUpdate.add(ordIns);
                    }
                }
                
                if(!ordInstListForUpdate.isEmpty()){
                    update ordInstListForUpdate;
                }
            }else{
                throw new CalloutException('HTTP callout failed: Not able to find any Active Integration handler -custom metadata type for '+actionType +' Record List - '+idsToProcess);
            }
                
        }catch(exception e){
            insert Utilities.getExceptionErrorLog('IntegrationHandler' , 'sendOrderInstallmentDataToIFB', e, String.valueOf(idsToProcess));
        }
    }
    public class flowInput{
        @InvocableVariable
        public List<id> idsListToProccess;
        @InvocableVariable
        public String actionType;  
    }
    
}