force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <label>API Configuration</label>
    <nameField>
        <displayFormat>ACN-{000000000}</displayFormat>
        <label>API Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense Sync Request</fullName>
            </value>
            <value>
                <fullName>LeaveUpdate</fullName>
            </value>
            <value>
                <fullName>Attendance Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Cancelled Sync</fullName>
            </value>
            <value>
                <fullName>Account Request</fullName>
                <isActive>false</isActive>
                <label>Account Request</label>
            </value>
            <value>
                <fullName>Meeting Request</fullName>
                <isActive>false</isActive>
                <label>Meeting Request</label>
            </value>
            <value>
                <fullName>Order Sync Request</fullName>
                <isActive>false</isActive>
                <label>Order Sync Request</label>
            </value>
            <value>
                <fullName>Product Query</fullName>
                <isActive>false</isActive>
                <label>Product Query</label>
            </value>
            <value>
                <fullName>Product Sync Request</fullName>
                <isActive>false</isActive>
                <label>Product Sync Request</label>
            </value>
            <value>
                <fullName>Sample Request</fullName>
                <isActive>false</isActive>
                <label>Sample Request</label>
            </value>
            <value>
                <fullName>Site Sync Request</fullName>
                <isActive>false</isActive>
                <label>Site Sync Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/JSON_Key__c.field-meta.xml
<CustomField>
    <fullName>JSON_Key__c</fullName>
    <label>JSON Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Expense_Line_Item__c</fullName>
            </value>
            <value>
                <fullName>Attendance__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Order_Installment__c</fullName>
            </value>
            <value>
                <fullName>OrderItem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <summarizedField>Expense_Line_Item__c.Approved_Amount__c</summarizedField>
    <summaryForeignKey>Expense_Line_Item__c.Expense__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Line_Item__c/Expense_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Line Item</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Handler__mdt/Integration_Handler__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type will be used to store the credential and other details  of third party system.</description>
    <label>Integration Handler</label>
    <pluralLabel>Integration Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Generation_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_Generation_URL__c</fullName>
    <label>Token Generation URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Token_Http_Method__c</fullName>
    <label>Token Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Handler__mdt/fields/Token_Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Token_Request_Body__c</fullName>
    <label>Token Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Installment__c/Order_Installment__c.object-meta.xml
<CustomObject>
    <label>Order Installment</label>
    <nameField>
        <displayFormat>OIN-{0000000}</displayFormat>
        <label>Order Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Installments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationHandlerTest.cls
@isTest
public class IntegrationHandlerTest {
    
    @testSetup
    static void setup() {
        List<Lead> leadObjList = TestDataFactory.getLeadList(1);
        Insert leadObjList;
        
        Expense__c expenseObj = TestDataFactory.createExpenseRecord();
        TestDataFactory.expenseLineIteamRecord(expenseObj.Id);
        API_Configuration__c apiConfigObj1 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj1.Parent_Object_Name__c = 'Expense__c';
        apiConfigObj1.Object_Name__c = 'Expense_Line_Item__c';
        apiConfigObj1.Include_Files__c = false;
        apiConfigObj1.Field_API_Name__c = 'Approved_Amount__c';
        apiConfigObj1.JSON_Key__c = 'test';
        apiConfigObj1.API_Type__c = 'Expense Sync Request';
        Insert apiConfigObj1;
        
        API_Configuration__c apiConfigObj2 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj2.Parent_Object_Name__c = null;
        apiConfigObj2.Object_Name__c = 'Expense__c';
        apiConfigObj2.Include_Files__c = false;
        apiConfigObj2.Field_API_Name__c = 'Advance_Amount__c';
        apiConfigObj2.JSON_Key__c = 'test';
        apiConfigObj2.API_Type__c = 'Expense Sync Request';
        Insert apiConfigObj2;
        
        API_Configuration__c apiConfigObj3 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj3.Parent_Object_Name__c = null;
        apiConfigObj3.Object_Name__c = 'Expense__c';
        apiConfigObj3.Include_Files__c = false;
        apiConfigObj3.Field_API_Name__c = 'Advance_Amount__c';
        apiConfigObj3.JSON_Key__c = 'test';
        apiConfigObj3.API_Type__c = 'Expense Sync Request';
        apiConfigObj3.Include_Files__c = true;
        Insert apiConfigObj3;
        
        TestDataFactory.contentDocumentLinkInsert(expenseObj.Id);
        Account accObj = TestDataFactory.createAccount();
        Order orderObj = TestDataFactory.createTestOrder(accObj.Id);
        Order_Installment__c orderInsObj = TestDataFactory.orderInstallmentRecordCreation(orderObj.Id);
 
    }
    
    @isTest
    public static void sendObejectDataToIFBInternalSysTest(){
        Test.startTest();
        Expense__c expenseObj = [SELECT Id From Expense__c Limit 1];
        IntegrationHandler.sendObejectDataToIFBInternalSys(new List<Id>{expenseObj.Id},'Lead Sync Request');
        Test.stopTest();
        
        Map<Id, Map<String, Object>> assertMap = IntegrationHandler.getFilesForRecords(new List<Id>{expenseObj.Id});
        System.assertEquals(1, assertMap.keySet().size(), 'Map should not empty');
        
        IntegrationHandler.flowInput wrapperObj = new IntegrationHandler.flowInput();
        wrapperObj.idsListToProccess = new List<id>{expenseObj.Id};
            wrapperObj.actionType = 'Expense Sync Request';
        IntegrationHandler.sendObejectDataToIFBInternalSysFromFlow(new List<IntegrationHandler.flowInput>{wrapperObj});
        
        Order orderObj = [SELECT Id From Order Limit 1];
        Order_Installment__c orderInsObj = [SELECT Id From Order_Installment__c Limit 1];
        TestDataFactory.contentDocumentLinkInsert(orderInsObj.Id);
        IntegrationHandler.sendOrderInstallmentDataToIFB(new List<Id>{orderInsObj.Id},'Expense Sync Request');
        try{
            IntegrationHandler.querySobjectWithSelectedField(new List<Id>(), new Set<String>(), new Map<String, Map<String, String>>(),new Map<String, String>(),'Retrieve');
        }catch(IllegalArgumentException exp){
            try{
            IntegrationHandler.querySobjectWithSelectedField(new List<Id>{orderInsObj.Id}, new Set<String>(), new Map<String, Map<String, String>>(),new Map<String, String>(),'Retrieve');
            }catch(IllegalArgumentException exp1){
                
            }
        }
        
    }
    
    @isTest
    static void testMakeHttpCallout() {
        // Test HTTP callout method separately
        String endpoint = 'https://example.com/api';
        String httpMethod = 'POST';
        String token = 'testToken';
        String requestBody = '{"test": "data"}';
        
        Test.startTest();
        HttpResponse mockResponse = new HttpResponse();
        mockResponse.setStatusCode(200);
        mockResponse.setBody('{"success": true}');
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockResponse));
        IntegrationHandler.generateToken([SELECT Id, Token_Generation_URL__c, Token_Http_Method__c, Token_Request_Body__c From Integration_Handler__mdt Limit 1]);
        HttpResponse response = IntegrationHandler.makeHttpCallout(endpoint, httpMethod, token, requestBody);
        Test.stopTest();
        System.assertEquals(200, response.getStatusCode(), 'Status code should be 200');
        System.assertEquals('{"success": true}', response.getBody(), 'Response body should match mock response');   
    }
    
    // Mock class for HTTP callout
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private HttpResponse response;
        
        public MockHttpResponseGenerator(HttpResponse response) {
            this.response = response;
        }
        
        public HttpResponse respond(HttpRequest req) {
            return response;
        }
    }
}