force-app/main/default/objects/API_Configuration__c/API_Configuration__c.object-meta.xml
<CustomObject>
    <label>API Configuration</label>
    <nameField>
        <displayFormat>ACN-{000000000}</displayFormat>
        <label>API Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Configuration__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense Sync Request</fullName>
            </value>
            <value>
                <fullName>LeaveUpdate</fullName>
            </value>
            <value>
                <fullName>Attendance Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Sync</fullName>
            </value>
            <value>
                <fullName>Purchase Order Cancelled Sync</fullName>
            </value>
            <value>
                <fullName>Account Request</fullName>
                <isActive>false</isActive>
                <label>Account Request</label>
            </value>
            <value>
                <fullName>Meeting Request</fullName>
                <isActive>false</isActive>
                <label>Meeting Request</label>
            </value>
            <value>
                <fullName>Order Sync Request</fullName>
                <isActive>false</isActive>
                <label>Order Sync Request</label>
            </value>
            <value>
                <fullName>Product Query</fullName>
                <isActive>false</isActive>
                <label>Product Query</label>
            </value>
            <value>
                <fullName>Product Sync Request</fullName>
                <isActive>false</isActive>
                <label>Product Sync Request</label>
            </value>
            <value>
                <fullName>Sample Request</fullName>
                <isActive>false</isActive>
                <label>Sample Request</label>
            </value>
            <value>
                <fullName>Site Sync Request</fullName>
                <isActive>false</isActive>
                <label>Site Sync Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/JSON_Key__c.field-meta.xml
<CustomField>
    <fullName>JSON_Key__c</fullName>
    <label>JSON Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Expense_Line_Item__c</fullName>
            </value>
            <value>
                <fullName>Attendance__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Order_Installment__c</fullName>
            </value>
            <value>
                <fullName>OrderItem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Configuration__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expense__c</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaveDataHandlerTest.cls
@isTest 
public class LeaveDataHandlerTest {
    @testSetup
    public static void testDataSetup(){
        API_Configuration__c apiConfigObj2 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj2.Parent_Object_Name__c = null;
        apiConfigObj2.Object_Name__c = 'Expense__c';
        apiConfigObj2.Include_Files__c = false;
        apiConfigObj2.Field_API_Name__c = 'Advance_Amount__c';
        apiConfigObj2.JSON_Key__c = 'startDate';
        apiConfigObj2.API_Type__c = 'LeaveUpdate';
        apiConfigObj2.Data_Type__c = 'Date';
        Insert apiConfigObj2;
        
        apiConfigObj2 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj2.Parent_Object_Name__c = null;
        apiConfigObj2.Object_Name__c = 'Expense__c';
        apiConfigObj2.Include_Files__c = false;
        apiConfigObj2.Field_API_Name__c = 'Advance_Amount__c';
        apiConfigObj2.JSON_Key__c = 'status';
        apiConfigObj2.API_Type__c = 'LeaveUpdate';
        apiConfigObj2.Data_Type__c = 'Integer';
        Insert apiConfigObj2;
        
        apiConfigObj2 = TestDataFactory.createAPIConfigRecordSingal(false);
        apiConfigObj2.Parent_Object_Name__c = null;
        apiConfigObj2.Object_Name__c = 'Expense__c';
        apiConfigObj2.Include_Files__c = false;
        apiConfigObj2.Field_API_Name__c = 'Advance_Amount__c';
        apiConfigObj2.JSON_Key__c = 'temp';
        apiConfigObj2.API_Type__c = 'LeaveUpdate';
        apiConfigObj2.Data_Type__c = 'Boolean';
        Insert apiConfigObj2;
        
        TestDataFactory.createEventRecordConditionaly(true);
        
    }
    
    @isTest
    public static void testSendLeaveRequest(){
        Test.startTest();
        HttpResponse mockResponse = new HttpResponse();
        mockResponse.setStatusCode(200);
        mockResponse.setBody('{"data": [{"startDate": "2024-09-22T08:00:00.000Z", "endDate": "2024-09-22T17:00:00.000Z", "status": "Approved"}]}');
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockResponse));
        LeaveDataHandler.sendLeaveRequest(new List<String>{'test'}, 1, 1);
        Test.stopTest();
        List<Log__c> logErrorObj = [SELECT Id From Log__c];
        System.assert(logErrorObj.size() > 0,'List Should Not Empty.');
    }
    
    @isTest
    public static void testHandleLeaveData(){
        List<Event> eventList = new List<Event>();
        eventList = [SELECT Id, Employee_Code__c, ActivityDate, Type From Event];
        LeaveDataHandler.upsertEvents(eventList);
        
        List<Object> leaveDataList = new List<Object>();
        // Create a map for each leave entry
        Map<String, Object> leaveEntry1 = new Map<String, Object>();
        leaveEntry1.put('startDate', '2024-09-22T08:00:00.000Z');
        leaveEntry1.put('endDate', '2024-09-22T17:00:00.000Z');
        leaveEntry1.put('status', '1');
        leaveEntry1.put('temp', true);
        leaveDataList.add(leaveEntry1);
        
        // You can add more entries as needed
        Map<String, Object> leaveEntry2 = new Map<String, Object>();
        leaveEntry2.put('startDate', '2024-09-23T08:00:00.000Z');
        leaveEntry2.put('endDate', '2024-09-23T17:00:00.000Z');
        leaveEntry2.put('status', '1');
        leaveEntry2.put('temp', true);
        leaveDataList.add(leaveEntry2);
        
        Map<String, Object> tempMap = new Map<String, Object>();
        tempMap.put('Data',leaveDataList);
        String str = JSON.serialize(tempMap);
        Test.startTest();
        LeaveDataHandler.handleLeaveData(str);
        Test.stopTest();
        List<Log__c> logErrorObj = [SELECT Id From Log__c];
        System.assert(logErrorObj.size() > 0,'List Should Not Empty.');
        Delete [SELECT Id From API_Configuration__c]; 
        LeaveDataHandler.handleLeaveData(str);
    }
    
    
    
    // Mock class for HTTP callout
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private HttpResponse response;
        
        public MockHttpResponseGenerator(HttpResponse response) {
            this.response = response;
        }
        
        public HttpResponse respond(HttpRequest req) {
            return response;
        }
    }
    
}